// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_MEA {
    static let rows = #"""
DXB|OMDB|Dubai International Airport|Dubai|Dubai|AE|DU|25.2498|55.3710|62|14590|P|L|1|5506549
TLV|LLBG|Ben Gurion International Airport|Tel Aviv|Tel Aviv|IL|M|32.0114|34.8867|135|13327|P|L|1|9209085
BGW|ORBI|Baghdad International Airport / New Al Muthana Air Base|Baghdad|Baghdad|IQ|BG|33.2625|44.2346|114|13124|P|L|1|11891888
BSR|ORMM|Basra International Airport|Basra|Basra|IQ|BA|30.5491|47.6621|11|13124|P|L|1|2493658
EBL|ORER|Erbil International Airport|Arbil|Arbil|IQ|AR|36.2360|43.9466|1341|15748|P|L|1|3510954
BJB|OIMN|Bojnord Airport|Bojnord|Bojnord|IR|28|37.4930|57.3082|3499|10582|P|M|1|300458
GBT|OING|Gorgan Airport|Gorgan|Gorgan|IR|27|36.9094|54.4013|-24|10827|P|M|0|1088486
IFN|OIFM|Isfahan Shahid Beheshti International Airport|Isfahan|Isfahan|IR|10|32.7551|51.8839|5059|14425|P|L|1|3734887
IKA|OIIE|Imam Khomeini International Airport|Tehran|Tehran|IR|23|35.4161|51.1522|3305|13772|P|L|1|8977143
KER|OIKK|Ayatollah Hashemi Rafsanjani International Airport|Kerman|Kerman|IR|08|30.2713|56.9497|5741|12635|P|L|1|902750
KSH|OICC|Shahid Ashrafi Esfahani Airport|Kermanshah|Kermanshah|IR|05|34.3459|47.1581|4307|11213|P|M|1|962438
LRR|OISL|Lar Airport|Lar|Lar|IR|07|27.6747|54.3833|2641|10397|P|M|1|185359
MHD|OIMM|Mashhad International Airport|Mashhad|Mashhad|IR|09|36.2348|59.6429|3263|12877|P|L|1|3500281
RAS|OIGG|Sardar-e-Jangal Airport|Rasht|Rasht|IR|01|37.3233|49.6178|-40|9571|P|M|1|1353813
SYZ|OISS|Shiraz Shahid Dastghaib International Airport|Shiraz|Shiraz|IR|07|29.5392|52.5898|4927|14345|P|L|1|2527379
TBZ|OITT|Tabriz International Airport|Tabriz|Tabriz|IR|03|38.1339|46.2350|4459|11825|P|L|1|3108095
XBJ|OIMB|Birjand International Airport|Birjand|Birjand|IR|29|32.8965|59.2813|4952|9521|P|L|1|292194
ZAH|OIZH|Zahedan International Airport|Zahedan|Zahedan|IR|11|29.4757|60.9062|4564|14042|P|L|1|668958
ZBR|OIZC|Chabahar Konarak International Airport|Konarak|Konarak|IR|11|25.4432|60.3822|13|12514|P|M|1|147783
BEY|OLBA|Beirut Rafic Hariri International Airport|Beirut|Beirut|LB|JL|33.8198|35.4874|87|12467|P|L|1|5154737
MCT|OOMS|Muscat International Airport|Muscat|Muscat|OM|MA|23.6002|58.2853|48|13386|P|L|1|2328585
MSH|OOMA|RAFO Masirah|Masirah|Masirah|OM|SH|20.6754|58.8905|64|10005|P|M|0|18329
SLL|OOSA|Salalah International Airport|Salalah|Salalah|OM|ZU|17.0387|54.0913|73|13123|P|L|1|173692
DOH|OTHH|Hamad International Airport|Doha|Doha|QA|DA|25.2731|51.6081|13|15912|P|L|1|1595606
ABT|OEBA|King Saud Bin Abdulaziz (Al Baha) Airport|Al-Baha|Al-Baha|SA|11|20.2985|41.6362|5486|10991|P|M|1|230054
AHB|OEAB|Abha International Airport|Abha|Abha|SA|14|18.2404|42.6566|6858|10991|P|L|1|843638
AQI|OEPA|QaisumahHafar Al-Batin International Airport|Qaisumah|Qaisumah|SA|04|28.3357|46.1271|1174|10007|P|L|1|341784
ELQ|OEGS|Prince Naif bin Abdulaziz International Airport|Qassim|Qassim|SA|05|26.3028|43.7744|2126|9843|P|L|1|1387016
JED|OEJN|King Abdulaziz International Airport|Jeddah|Jeddah|SA|02|21.6802|39.1574|48|13123|P|L|1|5445940
MED|OEMA|Prince Mohammad Bin Abdulaziz Airport|Medina|Medina|SA|03|24.5534|39.7051|2151|14222|P|L|1|2255684
RAE|OERR|Arar Domestic Airport|Arar|Arar|SA|08|30.9066|41.1382|1813|10007|P|M|1|148540
RAH|OERF|Rafha Domestic Airport|Rafha|Rafha|SA|08|29.6264|43.4906|1474|9834|P|M|1|150
RUH|OERK|King Khalid International Airport|Riyadh|Riyadh|SA|01|24.9576|46.6988|2049|13796|P|L|1|4876844
SHW|OESH|Sharurah Domestic Airport|Sharurah|Sharurah|SA|10|17.4669|47.1214|2363|11975|P|M|1|8365
TUU|OETB|Prince Sultan bin Abdulaziz International Airport|Tabuk|Tabuk|SA|07|28.3711|36.6249|2551|10991|P|L|1|658411
ULH|OEAO|Al-Ula International Airport|Al-Ula|Al-Ula|SA|03|26.4836|38.1170|2050|10007|P|L|1|68017
WAE|OEWD|Wadi Al Dawasir Domestic Airport|Wadi Al Dawasir|Wadi Al Dawasir|SA|01|20.5043|45.1996|2062|10007|P|M|1|24097
DEZ|OSDZ|Deir ez-Zor Airport|Deir ez-Zor|Deir ez-Zor|SY|DY|35.2854|40.1760|700|9843|P|M|0|381085
ADB|LTBJ|Adnan Menderes International Airport|Gaziemir|Gaziemir|TR|35|38.2924|27.1570|412|10630|P|L|1|5380600
AOE|LTBY|Hasan Polatkan Airport|Eskisehir|Eskisehir|TR|26|39.8116|30.5193|2588|8261|P|L|1|3544328
AYT|LTAI|Antalya International Airport|Antalya|Antalya|TR|07|36.8987|30.8005|177|11155|P|L|1|2677075
COV|LTDB|Cukurova International Airport|Tarsus|Tarsus|TR|33|36.8915|35.0712|35|11482|P|L|1|4114745
DIY|LTCC|Diyarbakr Airport|Diyarbakr|Diyarbakr|TR|21|37.8939|40.2010|2251|11644|P|M|1|1918399
ESB|LTAC|Esenboga International Airport|Ankara|Ankara|TR|06|40.1281|32.9951|3125|12303|P|L|1|5937573
GZT|LTAJ|Gaziantep Oguzeli International Airport|Gaziantep|Gaziantep|TR|27|36.9472|37.4787|2315|9842|P|L|1|3252780
IST|LTFM|Istanbul Airport|Istanbul|Istanbul|TR|34|41.2749|28.7321|325|13451|P|L|1|14274488
KYA|LTAN|Konya Airport|Konya|Konya|TR|42|37.9790|32.5619|3392|10990|P|L|1|2206276
NOP|LTCM|Sinop Airport|Sinop|Sinop, TR|TR|57|42.0183|35.0718|20|6482|P|M|1|127536
VAS|LTAR|Sivas Nuri Demirag Airport|Sivas|Sivas|TR|58|39.8138|36.9035|5239|12503|P|M|1|341086
ADE|OYAA|Aden International Airport|Aden|Aden|YE|AD|12.8296|45.0300|7|10171|P|L|1|1295460
AXK|OYAT|Ataq Airport|Ataq|Ataq|YE|SH|14.5513|46.8262|3735|9482|P|M|0|43215
RIY|OYRN|Riyan International Airport|Mukalla|Mukalla|YE|HD|14.6622|49.3753|54|9843|P|L|1|617122
SAH|OYSN|Sanaa International Airport|Sanaa|Sanaa|YE|SA|15.4763|44.2197|7216|10669|P|L|1|2488616
SCT|OYSQ|Socotra Airport|Mori|Mori|YE|SU|12.6321|53.9062|146|10827|P|M|1|12045
"""#
}
