// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_RUS {
    static let rows = #"""
ABA|UNAA|Abakan International Airport|Abakan|Abakan|RU|KK|53.7400|91.3850|831|10663|P|L|1|587886
AMV|ULDD|Amderma Airport|Amderma|Amderma|RU|NEN|69.7637|61.5567|13|6000|G|M|1|609
ARH|ULAA|Talagi Airport|Archangelsk|Archangelsk|RU|ARK|64.6003|40.7167|62|8202|P|M|1|469177
ASF|URWA|Astrakhan Narimanovo Boris M. Kustodiev International Airport|Astrakhan|Astrakhan|RU|AST|46.2828|48.0105|-65|10499|P|L|1|719583
BGS|UNKB|Boguchany Airport|Boguchany|Boguchany|RU|KYA|58.3806|97.4723|446|3938|P|S|0|11209
BKA|UNIB|Baykit Airport|Baykit|Baykit|RU|KYA|61.6767|96.3550|853|3581|P|M|0|3748
BQJ|UEBB|Batagay Airport|Batagay|Batagay|RU|SA|67.6480|134.6950|696|3000|G|S|1|4266
BQS|UHBB|Ignatyevo Airport|Blagoveschensk|Blagoveschensk|RU|AMU|50.4267|127.4155|638|9256|P|M|1|682393
BTK|UIBB|Bratsk Airport|Bratsk|Bratsk|RU|IRK|56.3696|101.7018|1610|10368|P|M|1|280515
BZK|UUBP|Bryansk International Airport|Bryansk|Bryansk|RU|BRY|53.2144|34.1760|663|7874|P|M|0|746776
CEE|ULWC|Cherepovets Airport|Cherepovets|Cherepovets|RU|VLG|59.2736|38.0158|377|8202|P|M|1|398863
CKH|UESO|Chokurdakh Airport|Chokurdah|Chokurdah|RU|SA|70.6231|147.9020|151|6233|P|M|1|2506
CZR|UIAR|Chara Airport|Chara|Chara|RU|ZAB|56.9144|118.2701|2201|5905|P|S|0|6339
DHG|DHG|Dalnegorsk Airport|Dalnegorsk|Dalnegorsk|RU|PRI|44.5587|135.4900|833|3000|G|S|0|44589
DKS|UODD|Dikson Airport|Dikson|Dikson|RU|KYA|73.5178|80.3797|47|4920|P|M|0|1113
DPT|DPT|Deputatskiy Airport|Deputatskiy|Deputatskiy|RU|SA|69.3925|139.8900|950|3000|G|S|1|3484
DYR|UHMA|Ugolny Yuri Ryktheu Airport|Anadyr|Anadyr|RU|CHU|64.7349|177.7410|194|11483|P|M|1|15604
EIE|UNII|Yeniseysk Airport|Yeniseysk|Yeniseysk|RU|KYA|58.4742|92.1125|253|7217|P|M|1|91542
ERG|UIKE|Yerbogachen Airport|Erbogachen|Erbogachen|RU|IRK|61.2750|108.0300|400|3000|G|S|0|2019
ESL|URWI|Elista Airport|Elista|Elista|RU|KL|46.3739|44.3309|501|10499|P|M|1|151167
ETL|UHTQ|Svetlaya Airport|Svetlaya|Svetlaya|RU|PRI|46.5417|138.3217|131|3000|G|S|0|1109
EYA|UHBE|Zeya Airport|Zeya|Zeya|RU|AMU|53.6870|127.0910|905|3000|G|S|0|30587
EYK|USHQ|Beloyarskiy Airport|Beloyarskiy|Beloyarskiy|RU|KHM|63.6869|66.6986|82|7028|P|M|1|27121
GDX|UHMM|Sokol Airport|Magadan|Magadan|RU|MAG|59.9110|150.7200|574|11326|P|M|1|112283
GOJ|UWGG|Nizhny Novgorod / Strigino International Airport|Nizhny Novgorod|Nizhny Novgorod|RU|NIZ|56.2274|43.7852|256|9843|P|L|1|2852220
GOY|UNIT|Tura Mountain Airport|Tura|Tura|RU|KYA|64.3335|100.4329|2044|4593|P|S|1|5444
GSV|UWSG|Gagarin International Airport|Saratov|Saratov|RU|SAR|51.7128|46.1711|103|9843|P|L|1|1460255
GVN|UHKM|Sovetskaya Gavan (Maygatka) Airport|Sovetskaya Gavan|Sovetskaya Gavan|RU|KHA|48.9251|140.0353|768|9842|P|M|0|70343
HMA|USHH|Khanty Mansiysk Airport|Khanty-Mansiysk|Khanty-Mansiysk|RU|KHM|61.0285|69.0861|76|9180|P|M|1|101466
HTA|UIAA|Chita-Kadala International Airport|Chita|Chita|RU|ZAB|52.0248|113.3058|2272|9430|P|L|1|465719
HTG|UOHH|Khatanga Airport|Khatanga|Khatanga|RU|KYA|71.9781|102.4910|95|8872|P|M|1|3205
IKS|UEST|Tiksi Airport|Tiksi|Tiksi|RU|SA|71.6977|128.9030|26|9845|P|M|1|5700
IKT|UIII|Irkutsk International Airport|Irkutsk|Irkutsk|RU|IRK|52.2667|104.3956|1675|11696|P|L|1|1255196
ITU|UHSI|Iturup Airport|Kurilsk|Kurilsk|RU|SAK|45.2564|147.9555|387|7546|P|S|1|1607
KHV|UHHH|Khabarovsk Novy Airport|Khabarovsk|Khabarovsk|RU|KHA|48.5283|135.1886|244|13124|P|M|1|612213
KJA|UNKL|Krasnoyarsk International Airport|Krasnoyarsk|Krasnoyarsk|RU|KYA|56.1757|92.4858|942|12139|P|L|1|1482926
KPW|UHMK|Keperveem Airport|Keperveem|Keperveem|RU|CHU|67.8450|166.1400|623|11482|P|M|1|5757
KRR|URKK|Krasnodar Pashkovsky International Airport|Krasnodar|Krasnodar|RU|KDA|45.0345|39.1742|118|9835|P|L|1|2868235
KVM|UHMO|Markovo Airport|Markovo|Markovo|RU|CHU|64.6654|170.4176|75|7874|G|S|1|150
KVX|USKK|Pobedilovo Airport|Kirov|Kirov|RU|KIR|58.5039|49.3478|479|7230|P|M|1|756274
KYZ|UNKY|Kyzyl Airport|Kyzyl|Kyzyl|RU|TY|51.6694|94.4006|2123|8858|P|M|1|153187
KZN|UWKD|Kazan International Airport|Kazan|Kazan|RU|TA|55.6062|49.2787|411|12303|P|L|1|1900495
LED|ULLI|Pulkovo Airport|St. Petersburg|St. Petersburg|RU|SPE|59.8003|30.2625|78|12402|P|L|1|10105429
MCX|URML|Makhachkala Uytash International Airport|Makhachkala|Makhachkala|RU|DA|42.8168|47.6523|12|8662|P|L|1|1559546
MJZ|UERR|Mirny Airport|Mirny|Mirny|RU|SA|62.5347|114.0390|1156|9187|P|M|1|42007
MMK|ULMM|Emperor Nicholas II Murmansk Airport|Murmansk|Murmansk|RU|MUR|68.7817|32.7508|266|8202|P|L|1|595582
MRV|URMM|Mineralnye Vody Airport|Mineralnyye Vody|Mineralnyye Vody|RU|STA|44.2251|43.0819|1054|12795|P|L|1|1747950
NER|UELL|Chulman Airport|Neryungri|Neryungri|RU|SA|56.9139|124.9140|2812|11811|P|M|1|86154
NJC|USNN|Nizhnevartovsk Airport|Nizhnevartovsk|Nizhnevartovsk|RU|KHM|60.9493|76.4836|177|10499|P|L|1|409226
NLI|UHNN|Nikolayevsk-na-Amure Airport|Nikolayevsk-na-Amure|Nikolayevsk-na-Amure|RU|KHA|53.1550|140.6500|170|6233|P|M|1|29642
NNM|ULAM|Naryan Mar Airport|Naryan Mar|Naryan Mar|RU|NEN|67.6400|53.1219|36|8202|P|M|1|48097
NOJ|USRO|Noyabrsk Airport|Noyabrsk|Noyabrsk|RU|YAN|63.1833|75.2700|446|8202|P|M|1|149137
NOZ|UNWW|Spichenkovo Airport|Novokuznetsk|Novokuznetsk|RU|KEM|53.8114|86.8772|1024|8789|P|M|1|1279513
NSK|UOOO|Alykel International Airport|Norilsk|Norilsk|RU|KYA|69.3080|87.3259|574|11254|P|L|1|251474
NUX|USMU|Novy Urengoy Airport|Novy Urengoy|Novy Urengoy|RU|YAN|66.0694|76.5203|210|8366|P|M|1|98741
NZG|UIUN|Nizhneangarsk International Airport|Nizhneangarsk|Nizhneangarsk|RU|BU|55.8008|109.5950|1545|5249|P|S|1|32886
ODO|UIKB|Bodaybo Airport|Bodaybo|Bodaybo|RU|IRK|57.8661|114.2430|919|5436|G|S|1|19837
OHO|UHOO|Okhotsk Airport|Okhotsk|Okhotsk|RU|KHA|59.4101|143.0565|45|6562|P|M|1|5570
OLZ|UEMO|Olyokminsk Airport|Olyokminsk|Olyokminsk|RU|SA|60.4018|120.4761|656|4265|P|M|1|9969
OMS|UNOO|Omsk Central Airport|Omsk|Omsk|RU|OMS|54.9631|73.3124|311|9435|G|L|1|1416676
OVB|UNNT|Novosibirsk Tolmachevo Airport|Novosibirsk|Novosibirsk|RU|NVS|55.0198|82.6187|365|11818|P|L|1|2058867
OVS|USHS|Sovetskiy Airport|Sovetskiy|Sovetskiy|RU|KHM|61.3266|63.6019|351|8202|P|M|1|69311
PEE|USPP|Perm International Airport|Perm|Perm|RU|PER|57.9145|56.0212|404|10520|P|L|1|1662494
PES|ULPB|Petrozavodsk Airport|Petrozavodsk|Petrozavodsk|RU|KR|61.8852|34.1547|151|8202|P|M|1|333241
PKC|UHPP|Yelizovo Airport|Petropavlovsk-Kamchatsky|Petropavlovsk-Kamchatsky|RU|KAM|53.1687|158.4511|131|11155|P|L|1|248879
PVS|UHMD|Provideniya Bay Airport|Chukotka|Chukotka|RU|CHU|64.3781|-173.2430|72|7190|G|M|0|2536
PWE|UHMP|Pevek Airport|Apapelgino|Apapelgino|RU|CHU|69.7833|170.5970|11|8202|P|M|1|4837
PYJ|UERP|Polyarny Airport|Yakutia|Yakutia|RU|SA|66.4004|112.0300|1660|10170|P|M|1|30533
ROV|URRP|Platov International Airport|Rostov-on-Don|Rostov-on-Don|RU|ROS|47.4939|39.9247|213|11811|P|L|0|4847049
SBT|USDA|Sabetta International Airport|Sabetta|Sabetta|RU|YAN|71.2192|72.0522|46|8858|P|M|1|150
SCW|UUYY|Syktyvkar Airport|Syktyvkar|Syktyvkar|RU|KO|61.6470|50.8451|342|8203|P|M|1|355471
SKX|UWPS|Saransk International Airport|Saransk|Saransk|RU|MO|54.1251|45.2123|676|9186|P|L|1|1065719
SLY|USDD|Salekhard Airport|Salekhard|Salekhard|RU|YAN|66.5908|66.6110|218|8917|P|M|1|86155
SVO|UUEE|Sheremetyevo International Airport|Moscow|Moscow|RU|MOS|55.9775|37.3867|622|12139|P|L|1|25727715
SVX|USSS|Koltsovo Airport|Yekaterinburg|Yekaterinburg|RU|SVE|56.7431|60.8027|764|9925|P|L|1|3442589
SYS|UERS|Saskylakh Airport|Saskylakh|Saskylakh|RU|SA|71.9279|114.0800|0|6000|G|M|1|1920
TGP|UNIP|Podkamennaya Tunguska Airport|Bor|Bor|RU|KYA|61.5897|89.9940|213|5597|P|M|0|2300
THX|UOTT|Turukhansk Airport|Turukhansk|Turukhansk|RU|KYA|65.7972|87.9353|128|5905|P|S|1|4774
TJM|USTR|Roshchino International Airport|Tyumen|Tyumen|RU|TYU|57.1790|65.3277|378|9852|P|L|1|1162213
UCT|UUYH|Ukhta Airport|Ukhta|Ukhta|RU|KO|63.5669|53.8047|482|8691|P|M|1|162361
UFA|UWUU|Ufa International Airport|Ufa|Ufa|RU|BA|54.5575|55.8744|449|12339|P|L|1|2165825
UHMF|UHMF|Omsukchan Airport|Omsukchan|Omsukchan|RU|MAG|62.4570|155.7450|1732|6000|G|M|1|5395
UHMH|UHMH|Susuman Airport|Susman|Susman|RU|MAG|62.7650|148.1470|2129|3000|G|S|1|9157
UHMN|UHMN|Omolon Airport|Omolon|Omolon|RU|CHU|65.2400|160.5400|869|3000|G|S|1|150
UHPK|UHPK|Ust'-Kamchatsk Airport|Ust'-Kamchatsk|Ust'-Kamchatsk|RU|KAM|56.2389|162.6900|200|4100|P|S|1|4939
UHS|RU-0802|Aleksandrovsk-Sakhalinskiy Airport|Aleksandrovsk-Sakhalinsk|Aleksandrovsk-Sakhalinsk|RU|SAK|50.8771|142.1756|12|3000|G|S|0|21686
UKX|UITT|Ust-Kut Airport|Ust-Kut|Ust-Kut|RU|IRK|56.8567|105.7300|2188|6561|P|M|1|51785
UMS|UEMU|Ust-Maya Airport|Ust-Maya|Ust-Maya|RU|SA|60.3574|134.4373|561|3000|G|S|1|3062
USDO|USDO|Tolka Airport|Tolka|Tolka|RU|YAN|63.9878|82.0509|92|3000|G|S|1|150
USK|UUYS|Usinsk Airport|Usinsk|Usinsk|RU|KO|66.0047|57.3672|262|8202|P|M|1|45739
USR|UEMT|Ust-Nera Airport|Ust-Nera|Ust-Nera|RU|SA|64.5500|143.1150|1805|5020|P|M|1|9148
UUS|UHSS|Yuzhno-Sakhalinsk International Airport|Yuzhno-Sakhalinsk|Yuzhno-Sakhalinsk|RU|SAK|46.8855|142.7175|59|11155|P|L|1|341228
VAQ|UNIW|Vanavara Airport|Vanavara|Vanavara|RU|KYA|60.3562|102.3096|892|4592|P|M|1|3090
VLU|ULOL|Velikiye Luki Airport|Velikiye Luki|Velikiye Luki|RU|PSK|56.3811|30.6078|328|6000|G|M|0|164866
VOG|URWW|Volgograd International Airport|Volgograd|Volgograd|RU|VGG|48.7813|44.3392|482|9186|P|L|1|1710240
VOZ|UUOO|Voronezh International Airport|Voronezh|Voronezh|RU|VOR|51.8143|39.2309|514|7546|P|M|1|1472749
VUS|ULWU|Velikiy Ustyug Airport|Velikiy Ustyug|Velikiy Ustyug|RU|VLG|60.7883|46.2600|331|5069|P|M|1|75928
VVO|UHWW|Vladivostok International Airport|Artyom|Artyom|RU|PRI|43.3963|132.1482|59|11483|P|L|1|1739683
VYI|UENW|Vilyuisk Airport|Vilyuisk|Vilyuisk|RU|SA|63.7567|121.6933|361|5249|P|M|1|14055
YKS|UEEE|Platon Oyunsky Yakutsk International Airport|Yakutsk|Yakutsk|RU|SA|62.0933|129.7710|325|11155|P|L|1|292299
YMK|USDK|Mys Kamenny Airport|Mys Kamennyi|Mys Kamennyi|RU|YAN|68.4677|73.5967|3|3000|G|S|0|1745
ZIX|UEVV|Zhigansk Airport|Zhigansk|Zhigansk|RU|SA|66.7965|123.3610|292|6000|G|M|1|3237
ZKP|UESU|Zyryanka Airport|Zyryanka|Zyryanka|RU|SA|65.7485|150.8889|140|6000|G|M|1|3627
"""#
}
