// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_EUE {
    static let rows = #"""
KFZ|LAKU|Kukes International Airport|Kukes|AL|07|42.0358|20.4160|1120|7211|P|M|0|170449
TIA|LATI|Tirana International Airport Mother Teresa|Rinas|AL|02|41.4147|19.7206|126|9843|P|L|1|1358891
BNX|LQBK|Banja Luka International Airport|Mahovljani|BA|SRP|44.9414|17.2975|400|8202|P|L|1|787814
OMO|LQMO|Mostar International Airport|Mostar|BA|BIH|43.2825|17.8461|156|7874|P|L|1|388750
SJJ|LQSA|Sarajevo International Airport|Sarajevo|BA|BIH|43.8246|18.3315|1708|8666|P|L|1|1130403
TZL|LQTZ|Tuzla International Airport|Dubrave Gornje|BA|BIH|44.4599|18.7236|784|8152|P|L|1|954177
BOJ|LBBG|Burgas Airport|Burgas|BG|02|42.5699|27.5152|135|10499|P|L|1|691095
GOZ|LBGO|Gorna Oryahovitsa Airport|Gorna Oryahovitsa|BG|04|43.1514|25.7129|285|8038|P|M|0|316843
PDV|LBPD|Plovdiv International Airport|Plovdiv|BG|16|42.0678|24.8508|597|8202|P|L|1|1299015
SOF|LBSF|Sofia Airport|Sofia|BG|22|42.6964|23.4177|1742|11811|P|L|1|1901241
VAR|LBWN|Varna Airport|Varna|BG|03|43.2321|27.8251|230|8258|P|L|1|767019
BQT|UMBB|Brest International Airport|Brest|BY|BR|52.1081|23.8968|468|8596|P|L|1|1480989
GME|UMGG|Gomel Airport|Gomel|BY|HO|52.5270|31.0167|472|8428|P|M|1|1625235
GNA|UMMG|Hrodna Airport|Hrodna|BY|HR|53.6020|24.0538|443|8399|P|M|0|694203
MSQ|UMMS|Minsk National Airport|Minsk|BY|MI|53.8881|28.0400|670|12139|P|L|1|2886783
MVQ|UMOO|Mogilev Airport|Mogilev|BY|MA|53.9549|30.0951|637|8422|P|M|1|760476
VTB|UMII|Vitebsk Vostochny Airport|Vitebsk|BY|VI|55.1265|30.3496|682|8550|P|M|0|611751
BRQ|LKTB|Brno-Turany Airport|Brno|CZ|JM|49.1513|16.6940|778|8694|P|M|1|1295993
JCL|LKCS|Ceske Budejovice South Bohemian Airport|Ceske Budejovice|CZ|JC|48.9482|14.4283|1417|8202|P|L|1|1098745
KLV|LKKV|Karlovy Vary Airport|Karlovy Vary|CZ|KA|50.2030|12.9150|1989|7054|P|L|1|1899019
OSR|LKMT|Leos Janacek Airport Ostrava|Mosnov|CZ|MO|49.6963|18.1111|844|11484|P|L|1|2902103
PED|LKPD|Pardubice Airport|Pardubice|CZ|PA|50.0150|15.7398|741|8203|P|L|1|1906124
PRG|LKPR|Vaclav Havel Airport Prague|Prague|CZ|PR|50.1009|14.2599|1247|12189|P|L|1|3380857
UHE|LKKU|Kunovice Airport|Uherske Hradiste|CZ|ZL|49.0294|17.4397|581|6562|P|M|0|382498
VOD|LKVO|Vodochody Airport|Vodochody|CZ|ST|50.2166|14.3958|919|8203|P|M|0|490528
EERU|EERU|Ruhnu Airfield|Ringsu|EE|74|57.7856|23.2624|10|1967|G|S|1|21869
EPU|EEPU|Parnu Airport|Parnu|EE|67|58.4190|24.4728|47|6463|P|M|1|118253
KDL|EEKA|Kardla Airport|Kardla|EE|39|58.9908|22.8307|18|4987|P|M|1|31710
TAY|EETU|Tartu Airport|Tartu|EE|7B|58.3074|26.6865|220|5905|P|M|1|258036
TLL|EETN|Lennart Meri Tallinn Airport|Tallinn|EE|37|59.4132|24.8326|131|11417|P|L|1|1344172
URE|EEKE|Kuressaare Airport|Kuressaare|EE|74|58.2299|22.5095|14|6561|P|M|1|38601
BWK|LDSB|Brac Airport|Gornji Humac|HR|17|43.2845|16.6784|1776|5774|P|M|1|108113
DBV|LDDU|Dubrovnik Ruer Boskovic Airport|Dubrovnik|HR|19|42.5622|18.2655|527|10597|P|L|1|191252
OSI|LDOS|Osijek Airport|Osijek(Klisa)|HR|14|45.4624|18.8113|290|8202|P|M|1|523420
PUY|LDPL|Pula Airport|Pula|HR|18|44.8935|13.9222|274|9678|P|L|1|277675
RJK|LDRI|Rijeka Airport|Rijeka(Omisalj)|HR|08|45.2164|14.5709|278|8164|P|L|1|439018
SPU|LDSP|Split Saint Jerome Airport|Split|HR|17|43.5389|16.2980|79|8366|P|L|1|414163
ZAD|LDZD|Zadar Airport|Zadar|HR|13|44.0970|15.3536|289|8202|P|L|1|256212
ZAG|LDZA|Zagreb Franjo Tuman International Airport|Velika Gorica|HR|01|45.7429|16.0688|353|10669|P|L|1|1410603
BUD|LHBP|Budapest Liszt Ferenc International Airport|Budapest|HU|BU|47.4302|19.2624|495|12162|P|L|1|8566540
DEB|LHDC|Debrecen International Airport|Debrecen|HU|HB|47.4895|21.6163|359|8196|P|L|1|1515027
LHPR|LHPR|Gyor-Per Airport|Gyor|HU|GS|47.6284|17.8047|424|6660|P|M|1|863718
PEV|LHPP|Pecs-Pogany International Airport|Pecs|HU|BA|45.9889|18.2420|651|4922|P|L|1|1164106
SOB|LHSM|HevizBalaton Airport|Sarmellek|HU|ZA|46.6864|17.1591|408|8202|P|M|1|428926
KUN|EYKA|Kaunas International Airport|Kaunas|LT|KU|54.9640|24.0858|256|10663|P|L|1|1053890
PLQ|EYPA|Palanga International Airport|Palanga|LT|KL|55.9732|21.0939|33|7480|P|L|1|362542
SQQ|EYSA|Siauliai International Airport|Siauliai|LT|SA|55.8939|23.3950|443|11483|P|M|0|146936
VNO|EYVI|Vilnius International Airport|Vilnius|LT|VL|54.6341|25.2858|648|8251|P|L|1|1498178
LPX|EVLA|Liepaja International Airport|Liepaja|LV|112|56.5175|21.0969|16|6568|P|L|0|135156
RIX|EVRA|Riga International Airport|Riga|LV|062|56.9208|23.9707|36|10499|P|L|1|1335804
BZY|LUBL|Balti-Leadoveni International Airport|Balti|MD|RS|47.8377|27.7811|758|7251|P|M|0|288577
RMO|LUKK|Chisinau International Airport|Chisinau|MD|CU|46.9277|28.9317|399|11778|P|L|1|2040172
TGD|LYPG|Podgorica Airport / Podgorica Golubovci Airbase|Podgorica|ME|16|42.3594|19.2519|141|8202|P|L|1|559620
TIV|LYTV|Tivat Airport|Tivat|ME|19|42.4047|18.7233|20|8208|P|M|1|106088
OHD|LWOH|Ohrid St. Paul the Apostle Airport|Ohrid|MK|003|41.1800|20.7423|2313|8366|P|L|1|1038647
SKP|LWSK|Skopje International Airport|Ilinden|MK|008|41.9581|21.6226|781|9678|P|L|1|1727021
BZG|EPBY|Ignacy Jan Paderewski Bydgoszcz Airport|Bydgoszcz|PL|KP|53.0968|17.9777|235|8202|P|M|1|1099634
GDN|EPGD|Gdansk Lech Waesa Airport|Gdansk|PL|PM|54.3776|18.4662|489|9186|P|L|1|2433296
IEG|EPZG|Zielona Gora-Babimost Airport|Nowe Kramsko|PL|LB|52.1385|15.7986|194|8202|P|M|1|583262
KRK|EPKK|Krakow John Paul II International Airport|Balice|PL|MA|50.0777|19.7848|791|8366|P|L|1|3070100
KTW|EPKT|Katowice Wojciech Korfanty International Airport|Katowice|PL|SL|50.4760|19.0807|995|10499|P|L|1|3384204
LCJ|EPLL|odz Wadysaw Reymont Airport|odz|PL|LD|51.7219|19.3981|604|8202|P|L|1|1905428
LUZ|EPLB|Lublin Airport|Lublin|PL|LU|51.2402|22.7135|633|8268|P|L|1|1238519
POZ|EPPO|Poznan-awica Airport|Poznan|PL|WP|52.4216|16.8234|308|8215|P|L|1|1889293
RDO|EPRA|Warsaw Radom Airport|Radom|PL|MZ|51.3894|21.2147|610|8202|P|M|1|586788
RZE|EPRZ|Rzeszow-Jasionka Airport|Jasionka|PL|PK|50.1098|22.0242|693|10498|P|L|1|1823130
SZY|EPSY|Olsztyn-Mazury Airport|Szymany|PL|WN|53.4819|20.9377|463|8202|P|M|1|630321
SZZ|EPSC|Solidarity SzczecinGoleniow Airport|Szczecin(Glewice)|PL|ZP|53.5847|14.9022|154|8202|P|L|1|1325976
WAW|EPWA|Warsaw Chopin Airport|Warsaw|PL|MZ|52.1657|20.9671|362|12106|P|L|1|3789531
WMI|EPMO|Warsaw Modlin Airport|Nowy Dwor Mazowiecki|PL|MZ|52.4511|20.6518|341|8202|P|L|1|1626415
WRO|EPWR|Copernicus Wrocaw Airport|Wrocaw|PL|DS|51.1037|16.8821|404|8212|P|L|1|3443054
ARW|LRAR|Arad International Airport|Arad|RO|AR|46.1761|21.2643|352|6562|P|M|1|645867
BAY|LRBM|Maramures International Airport|Tautii-Magheraus|RO|MM|47.6584|23.4644|605|7054|P|M|1|904743
BBU|LRBS|Bucharest Baneasa Aurel Vlaicu International Airport|Bucharest|RO|B|44.5031|26.1029|297|10499|P|L|1|4267665
BCM|LRBC|Bacau George Enescu International Airport|Bacau|RO|BC|46.5219|26.9103|607|8203|P|L|1|2124265
CLJ|LRCL|Avram Iancu Cluj International Airport|Cluj-Napoca|RO|CJ|46.7860|23.6857|1039|6693|P|L|1|1554693
CND|LRCK|Mihail Kogalniceanu International Airport|Constanta|RO|CT|44.3622|28.4883|353|11483|P|L|1|1473878
CRA|LRCV|Craiova International Airport|Craiova|RO|DJ|44.3181|23.8886|626|8203|P|L|1|2386947
CSB|LRCS|Caransebes Airport|Caransebes|RO|CS|45.4201|22.2525|866|6562|P|M|0|285684
GHV|LRBV|Brasov-Ghimbav International Airport|Brasov (Ghimbav)|RO|BV|45.7056|25.5229|1740|9252|P|L|1|1903282
IAS|LRIA|Iasi International Airport|Iasi|RO|IS|47.1796|27.6214|411|7874|P|L|1|1700805
OMR|LROD|Oradea International Airport|Oradea|RO|BH|47.0253|21.9025|465|8267|P|L|1|1175961
OTP|LROP|Bucharest Henri Coanda International Airport|Otopeni|RO|IF|44.5718|26.1033|314|11484|P|L|1|3372808
SBZ|LRSB|Sibiu International Airport|Sibiu|RO|SB|45.7858|24.0867|1496|8629|P|L|1|1554052
SCV|LRSV|Suceava Stefan cel Mare International Airport|Suceava|RO|SV|47.6875|26.3541|1375|8070|P|L|1|2169420
SUJ|LRSM|Satu Mare International Airport|Satu Mare|RO|SM|47.7033|22.8857|405|8160|P|M|1|775603
TCE|LRTC|Tulcea Danube Delta Airport|Mihail Kogalniceanu|RO|TL|45.0625|28.7143|200|6517|P|M|0|445821
TGM|LRTM|Targu Mures Transilvania International Airport|Recea|RO|MS|46.4677|24.4125|963|6562|P|M|1|693797
TSR|LRTR|Timisoara Traian Vuia International Airport|Timisoara|RO|TM|45.8099|21.3379|348|11483|P|L|1|1592953
BEG|LYBE|Belgrade Nikola Tesla Airport|Belgrade|RS|00|44.8184|20.3091|335|11483|P|L|1|2822077
INI|LYNI|Nis Constantine the Great Airport|Nis|RS|20|43.3365|21.8562|648|8202|P|L|1|956414
KVO|LYKV|Morava Airport|Kraljevo|RS|18|43.8175|20.5867|686|7431|P|M|1|449639
UZC|LYUZ|Ponikve Airport|Stapari|RS|16|43.8989|19.6977|2966|10130|P|M|0|121789
LJU|LJLJ|Ljubljana Joze Pucnik Airport|Zgornji Brnik|SI|012|46.2237|14.4576|1273|10827|P|L|1|806272
MBX|LJMB|Maribor Edvard Rusjan Airport|Maribor|SI|160|46.4799|15.6861|876|8202|P|M|1|401180
POW|LJPZ|Portoroz Airport|Secovlje|SI|090|45.4720|13.6160|7|3939|P|M|0|104242
BTS|LZIB|M. R. Stefanik Airport|Bratislava|SK|BL|48.1702|17.2127|436|10466|P|L|1|2559932
ILZ|LZZI|Zilina-Dolny Hricov Airport|Dolny Hricov|SK|ZI|49.2333|18.6134|1020|3773|P|M|0|380165
KSC|LZKZ|Kosice International Airport|Kosice|SK|KI|48.6631|21.2411|755|10171|P|M|1|860314
PZY|LZPP|Piestany Airport|Piestany|SK|TA|48.6252|17.8284|545|6562|P|M|0|311572
SLD|LZSL|Sliac Airport|Sliac|SK|BC|48.6378|19.1341|1043|7874|P|M|1|761821
TAT|LZTT|Poprad-Tatry Airport|Poprad|SK|PV|49.0710|20.2414|2356|8530|P|M|1|693248
CKC|UKKE|Cherkasy International Airport|Cherkasy|UA|71|49.4156|31.9953|375|8180|P|M|0|1366797
CWC|UKLN|Chernivtsi International Airport|Chernivtsi|UA|77|48.2593|25.9808|826|7270|P|M|0|676339
DNK|UKDD|Dnipro International Airport|Dnipro|UA|12|48.3572|35.1006|481|9320|P|M|0|2069766
ERD|UKDB|Berdyansk Airport|Berdyansk|UA|23|46.8150|36.7581|171|8202|P|M|0|592694
HMJ|UKLH|Khmelnytskyi Airport|Khmelnytskyi|UA|68|49.3597|26.9334|1150|7219|P|M|0|706568
HRK|UKHH|Kharkiv International Airport|Kharkiv|UA|A|49.9269|36.2908|508|7285|P|M|0|4191271
IEV|UKKK|Igor Sikorsky Kyiv International Airport (Zhuliany)|Kyiv|UA|30|50.4019|30.4519|587|7579|P|M|0|4591477
IFO|UKLI|Ivano-Frankivsk International Airport|Ivano-Frankivsk|UA|26|48.8842|24.6861|919|8226|P|M|0|793261
KBP|UKBB|Boryspil International Airport|Boryspil|UA|32|50.3450|30.8947|427|13123|P|L|0|4806878
KHE|UKOH|Kherson International Airport|Kherson|UA|65|46.6758|32.5064|148|8202|P|M|0|560193
KWG|UKDR|Kryvyi Rih International Airport|Kryvyi Rih|UA|12|48.0433|33.2100|408|8202|P|M|0|1666264
LWO|UKLL|Lviv International Airport|Lviv|UA|46|49.8125|23.9561|1071|10843|P|L|0|2002889
MPW|UKCM|Mariupol International Airport|Mariupol|UA|14|47.0761|37.4496|251|8431|P|M|0|3199286
NLV|UKON|Mykolaiv International Airport [CLOSED]|Mykolaiv|UA|48|47.0579|31.9198|184|8438|P|M|0|901906
ODS|UKOO|Odesa International Airport|Odesa|UA|51|46.4272|30.6726|172|9186|P|L|0|1769434
OZH|UKDE|Zaporizhzhia International Airport|Zaporizhia|UA|23|47.8670|35.3147|373|8210|P|M|0|1518463
PLV|UKHP|Suprunovka Airport|Poltava|UA|53|49.5686|34.3972|505|6000|G|M|0|1692071
RWN|UKLR|Rivne International Airport|Rivne|UA|19|50.6071|26.1416|755|8615|P|M|0|1021184
SIP|UKFF|Simferopol International Airport|Simferopol|UA|43|45.0522|33.9751|639|12142|P|L|0|2374876
UDJ|UKLU|Uzhhorod International Airport|Uzhhorod|UA|21|48.6343|22.2634|383|6686|P|M|0|480877
VIN|UKWW|Vinnytsia/Gavyryshivka International Airport|Vinnitsa|UA|05|49.2425|28.6138|961|8175|P|M|0|963172
ZTR|UKKV|Zhytomyr Airport|Zhytomyr|UA|18|50.2706|28.7386|0|6000|G|M|0|1079381
PRN|BKPR|Pristina Adem Jashari International Airport|Prishtina|XK|01|42.5728|21.0358|1789|9974|P|L|1|1564561
"""#
}
