// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_CAM {
    static let rows = #"""
BGK|MZBG|Big Creek Airport|Big Creek|BZ|SC|16.5194|-88.4079|22|3000|G|S|1|27755
BZE|MZBZ|Philip S. W. Goldson International Airport|Belize City|BZ|BZ|17.5400|-88.3036|15|9678|P|L|1|111167
CUK|MZCK|Caye Caulker Airport|Caye Caulker|BZ|BZ|17.7350|-88.0329|2|6000|G|M|1|26751
CYC|MZCP|Caye Chapel Airport|Caye Chapel|BZ|BZ|17.6838|-88.0450|3|6000|G|M|1|26582
CZH|MZCZ|Corozal Airport|Corozal|BZ|CZL|18.3822|-88.4119|40|2198|P|M|1|92058
DGA|MZPB|Dangriga Airport|Dangriga|BZ|SC|16.9825|-88.2310|10|6000|G|M|1|43950
INB|MZSV|Independence Airport|Independence|BZ|SC|16.5346|-88.4416|18|3000|G|S|1|28438
ORZ|MZTH|H.E Alfredo Martinez (Tower Hill) Airstrip|Orange Walk|BZ|OW|18.0468|-88.5839|69|3000|G|S|1|26297
PLJ|MZPL|Placencia Airport|Placencia|BZ|SC|16.5370|-88.3615|3|2133|P|M|1|76143
PND|MZPG|Punta Gorda Airport|Punta Gorda|BZ|TOL|16.1024|-88.8083|7|2372|P|S|1|61212
SJX|BZ-SJX|Sartaneja Airport|Sartaneja|BZ|CZL|18.3561|-88.1308|3|2510|G|M|0|21532
SPR|MZSP|John Greif II Airport|San Pedro|BZ|CY|17.9139|-87.9711|4|6000|G|M|1|31691
TZA|MZBE|Sir Barry Bowen Municipal Airport|Belize City|BZ|BZ|17.5172|-88.1958|8|6000|G|M|1|50671
BAI|MRBA|Buenos Aires Airport|Punta Arenas|CR|P|9.1639|-83.3302|1214|3248|P|M|0|27511
BCL|MRBC|Barra del Colorado Airport|Pococi|CR|L|10.7687|-83.5856|3|3281|P|M|0|15572
FON|MRAN|La Fortuna Arenal Airport|La Fortuna|CR|A|10.4693|-84.5791|342|2625|P|M|1|90136
GLF|MRGF|Golfito Airport|Golfito|CR|P|8.6540|-83.1822|49|4593|P|M|1|45786
GPL|MRGP|Guapiles Airport|Pococi|CR|L|10.2172|-83.7970|883|3609|P|M|0|55676
LIO|MRLM|Limon International Airport|Limon|CR|L|9.9580|-83.0220|7|5906|P|M|1|85259
LIR|MRLB|Daniel Oduber Quiros International Airport|Liberia|CR|G|10.5933|-85.5444|270|9022|P|L|1|152358
LSL|MRLC|Los Chiles Airport|Los Chiles|CR|A|11.0353|-84.7061|131|4265|P|M|0|44159
MRAO|MRAO|Aerotortuguero Airport|Roxana|CR|L|10.4200|-83.6095|92|3118|P|M|1|63319
NOB|MRNS|Nosara Airport|Nicoya|CR|G|9.9765|-85.6530|33|3281|P|M|1|28128
OTR|MRCC|Coto 47 Airport|Corredores|CR|P|8.6016|-82.9688|26|3281|P|M|0|32470
PJM|MRPJ|Puerto Jimenez Airport|Puerto Jimenez|CR|P|8.5333|-83.3000|7|2707|G|M|1|32938
PMZ|MRPM|Palmar Sur Airport|Palmar Sur|CR|P|8.9510|-83.4686|49|4570|P|M|0|20448
SJO|MROC|Juan Santamaria International Airport|San Jose (Alajuela)|CR|A|9.9939|-84.2088|3021|9882|P|L|1|815310
SYQ|MRPV|Tobias Bolanos International Airport|San Jose|CR|SJ|9.9571|-84.1398|3287|5138|P|M|1|449671
UPL|MRUP|Upala Airport|Upala|CR|A|10.8922|-85.0162|184|3536|P|M|0|44327
XQP|MRQP|Quepos Managua Airport|Quepos|CR|P|9.4432|-84.1298|85|3609|P|M|1|94674
AAZ|MGQZ|Quezaltenango Airport|Quezaltenango|GT|QZ|14.8656|-91.5020|7779|6900|P|S|1|625114
CBV|MGCB|Coban Airport|Coban|GT|AV|15.4690|-90.4067|4339|3340|P|M|0|411120
FRS|MGMM|Mundo Maya International Airport|San Benito|GT|PE|16.9137|-89.8661|427|9842|P|M|1|135280
GSJ|MGSJ|San Jose Airport|Puerto San Jose|GT|ES|13.9362|-90.8358|29|6595|P|M|0|236033
GUA|MGGT|La Aurora International Airport|Guatemala City|GT|GU|14.5829|-90.5275|4952|9800|P|L|1|5259360
HUG|MGHT|Huehuetenango Airport|Huehuetenango|GT|HU|15.3167|-91.5056|6135|3000|G|S|1|467865
PBR|MGPB|Puerto Barrios Airport|Puerto Barrios|GT|IZ|15.7309|-88.5838|33|8880|P|M|1|391278
RER|MGRT|Retalhuleu Airport|Retalhuleu|GT|RE|14.5214|-91.6970|656|5065|P|M|1|1089659
RUV|MGRB|Rubelsanto Airport|Rubelsanto|GT|AV|15.9920|-90.4453|426|4690|P|M|0|129635
GJA|MHNJ|La Laguna Airport|Guanaja|HN|IB|16.4454|-85.9066|49|3990|P|M|1|76985
LCE|MHLC|Goloson International Airport|La Ceiba|HN|AT|15.7425|-86.8530|39|9875|P|M|1|663036
PEU|MHPL|Puerto Lempira Airport|Puerto Lempira|HN|GD|15.2622|-83.7812|33|3000|G|S|1|31957
RTB|MHRO|Juan Manuel Galvez International Airport|Coxen Hole|HN|IB|16.3168|-86.5230|39|7349|P|L|1|231152
SAP|MHLM|Ramon Villeda Morales International Airport|San Pedro Sula|HN|CR|15.4526|-87.9236|91|9203|P|L|1|1849704
TEA|MHTE|Tela Airport|Tela|HN|AT|15.7759|-87.4758|7|4415|P|M|0|112887
TGU|MHTG|Toncontin Airport|Tegucigalpa|HN|FM|14.0609|-87.2172|3294|6112|P|M|1|1405087
TJI|MHTJ|Trujillo Airport|Trujillo|HN|CL|15.9266|-85.9386|3|3515|P|M|0|195866
UII|MHUT|Utila Airport|Utila Island|HN|IB|16.1131|-86.8803|29|3000|G|S|1|52040
XPL|MHPR|Palmerola International Airport|Palmerola|HN|CM|14.3824|-87.6212|2061|8064|P|L|1|1514305
BEF|MNBL|Bluefields Airport|Bluefields|NI|AS|11.9910|-83.7741|20|6625|P|M|1|103125
MGA|MNMG|Augusto C. Sandino (Managua) International Airport|Managua|NI|MN|12.1415|-86.1682|194|8012|P|L|1|2648316
PUZ|MNPC|Puerto Cabezas Airport|Puerto Cabezas|NI|AN|14.0472|-83.3867|52|8130|P|M|1|47208
RNI|MNCI|Corn Island Airport|Corn Island|NI|AS|12.1748|-83.0594|1|6234|P|S|1|10283
BFQ|MPPI|Bahia Pina Airport|Puerto Pina|PA|5|7.5874|-78.1799|14|3000|G|S|1|9166
BLB|MPPA|Panama Pacifico International Airport|Panama City|PA|10|8.9148|-79.5996|52|8500|P|S|1|130836
BOC|MPBO|Bocas del Toro 'Isla Colon' International Airport|Isla Colon|PA|1|9.3408|-82.2508|10|4921|P|M|1|44735
CHX|MPCH|Changuinola Captain Manuel Nino International Airport|Changuinola|PA|1|9.4590|-82.5151|19|3609|P|M|1|58257
CTD|MPCE|Alonso Valderrama Airport|Chitre|PA|6|7.9878|-80.4098|33|4921|P|M|1|176845
DAV|MPDA|Enrique Malek International Airport|David|PA|4|8.3890|-82.4364|89|8530|P|M|1|199987
ONX|MPEJ|Enrique Adolfo Jimenez Airport|Colon|PA|3|9.3566|-79.8674|25|8858|P|M|1|218483
OTD|MPRA|Raul Arias Espinoza Airport|Contadora Island|PA|8|8.6288|-79.0347|43|2297|G|S|1|25568
PAC|MPMG|Marcos A. Gelabert International Airport|Albrook|PA|8|8.9733|-79.5556|31|5906|P|M|1|509096
PDM|MPPD|Capt. J. Montenegro Airport|Pedasi|PA|7|7.5348|-80.0433|148|3281|P|S|1|18643
PTY|MPTO|Tocumen International Airport|Tocumen|PA|8|9.0714|-79.3835|135|10006|P|L|1|958625
RIH|MPSM|Scarlett Martinez International Airport|Rio Hato|PA|2|8.3759|-80.1279|105|8038|P|S|1|54732
SYP|MPSA|Ruben Cantu Airport|Santiago|PA|9|8.0856|-80.9453|272|3937|P|M|0|101173
ILS|MSSS|Ilopango International Airport|San Salvador|SV|SS|13.6995|-89.1199|2027|7349|P|M|1|1509010
SAL|MSLP|El Salvador International Airport Saint Oscar Arnulfo Romero y Galdamez|San Salvador (San Luis Talpa)|SV|PA|13.4445|-89.0558|101|10500|P|L|1|1535255
"""#
}
