// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows {
    static let groups: [String] = [AirportRows_NAM.rows, AirportRows_CAM.rows, AirportRows_CAR.rows, AirportRows_SAM.rows, AirportRows_EUW.rows, AirportRows_EUE.rows, AirportRows_NRD.rows, AirportRows_RUS.rows, AirportRows_MEA.rows, AirportRows_NAF.rows, AirportRows_CAS.rows, AirportRows_SAS.rows, AirportRows_EAS.rows, AirportRows_SEA.rows, AirportRows_OCE.rows, AirportRows_SSA.rows]
}
