// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_CAR {
    static let rows = #"""
ANU|TAPA|V. C. Bird International Airport|Osbourn|Osbourn|AG|03|17.1367|-61.7927|62|9003|P|L|1|114097
AUA|TNCA|Queen Beatrix International Airport|Oranjestad|Oranjestad|AW|A|12.5011|-70.0143|60|9000|P|L|1|233843
BGI|TBPB|Grantley Adams International Airport|Bridgetown|Bridgetown|BB|01|13.0747|-59.4910|169|11000|P|L|1|119425
FPO|MYGF|Grand Bahama International Airport|Freeport|Freeport|BS|FP|26.5580|-78.6956|7|11019|P|L|1|114900
LGI|MYLD|Deadman's Cay Airport|Deadman's Cay|Deadman's Cay|BS|LI|23.1790|-75.0936|9|4000|P|M|1|1800
NAS|MYNN|Lynden Pindling International Airport|Nassau|Nassau|BS|NP|25.0390|-77.4662|16|11353|P|L|1|214146
SML|MYLS|Stella Maris Airport|Stella Maris|Stella Maris|BS|LI|23.5823|-75.2686|10|4000|P|M|1|1032
ZSA|MYSM|San Salvador International Airport|San Salvador|San Salvador, BS|BS|SS|24.0630|-74.5232|24|8000|P|L|1|1501
CMW|MUCM|Ignacio Agramonte International Airport|Camaguey|Camaguey|CU|09|21.4199|-77.8480|413|9842|P|L|1|765866
HAV|MUHA|Jose Marti International Airport|Havana|Havana|CU|03|22.9892|-82.4091|210|13123|P|L|1|6377467
HOG|MUHG|Frank Pais International Airport|Holguin|Holguin|CU|11|20.7851|-76.3155|361|10624|P|L|1|776394
SCU|MUCU|Antonio Maceo International Airport|Santiago|Santiago, CU|CU|13|19.9747|-75.8355|249|13130|P|L|1|875234
SNU|MUSC|Abel Santamaria International Airport|Santa Clara|Santa Clara|CU|05|22.4922|-79.9431|338|9898|P|L|1|1152898
VRO|MUKW|Kawama Airport|Santa Marta|Santa Marta, CU|CU|04|23.1240|-81.3016|16|4850|P|M|0|261015
CUR|TNCC|Hato International Airport|Willemstad|Willemstad|CW|A|12.1889|-68.9598|29|11188|P|L|1|219501
BRX|MDBH|Maria Montez International Airport|Barahona|Barahona|DO|04|18.2515|-71.1204|10|9843|P|M|1|254418
SDQ|MDSD|Las Americas International Airport|Santo Domingo|Santo Domingo|DO|01|18.4297|-69.6689|59|11000|P|L|1|2624116
STI|MDST|Cibao International Airport|Santiago|Santiago, DO|DO|25|19.4041|-70.6044|565|8595|P|L|1|2192276
GND|TGPY|Maurice Bishop International Airport|Saint George's|Saint George's|GD|GE|12.0040|-61.7853|41|9003|P|L|1|22236
PTP|TFFR|Maryse Conde International Airport|Pointe-a-Pitre|Pointe-a-Pitre|GP|A|16.2654|-61.5328|36|11499|P|L|1|278670
CAP|MTCH|Cap Haitien International Airport|Cap Haitien|Cap Haitien|HT|ND|19.7255|-72.2007|10|8701|P|L|1|992227
PAP|MTPP|Toussaint Louverture International Airport|Port-au-Prince|Port-au-Prince|HT|OU|18.5800|-72.2926|122|9974|P|L|1|3955285
KIN|MKJP|Norman Manley International Airport|Kingston|Kingston|JM|01|17.9357|-76.7875|10|8900|P|L|1|1437146
MBJ|MKJS|Sangster International Airport|Montego Bay|Montego Bay|JM|08|18.5034|-77.9132|4|10039|P|L|1|361168
SKB|TKPK|Robert L. Bradshaw International Airport|Basseterre|Basseterre|KN|A|17.3108|-62.7191|170|7602|P|L|1|31894
GCM|MWCR|Owen Roberts International Airport|George Town|George Town|KY|GC|19.2928|-81.3577|8|7867|P|L|1|461950
FDF|TFFF|Martinique Aime Cesaire International Airport|Fort-de-France|Fort-de-France|MQ|A|14.5910|-61.0032|16|9843|P|L|1|314890
SJU|TJSJ|Luis Munoz Marin International Airport|San Juan|San Juan|PR|A|18.4394|-66.0018|9|10002|P|L|1|1413631
SXM|TNCM|Princess Juliana International Airport|Sint Maarten|Sint Maarten|SX|A|18.0410|-63.1089|13|7546|P|L|1|63607
PLS|MBPV|Providenciales International Airport|Providenciales|Providenciales|TC|PR|21.7737|-72.2683|15|9199|P|L|1|33110
SLX|MBSY|Salt Cay Airport|Salt Cay|Salt Cay|TC|SL|21.3330|-71.2000|3|3000|G|S|1|383
POS|TTPP|Piarco International Airport|Port of Spain|Port of Spain|TT|TUP|10.5953|-61.3376|58|10500|P|L|1|507446
STT|TIST|Cyril E. King Airport|Charlotte Amalie|Charlotte Amalie|VI|ST|18.3371|-64.9773|23|7000|P|L|1|131394
"""#
}
