// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_SSA {
    static let rows = #"""
CBT|FNCT|Catumbela Airport|Catumbela|Catumbela|AO|BGU|-12.4792|13.4869|23|12139|P|M|1|1055170
DUE|FNDU|Dundo Airport|Chitato|Chitato|AO|LNO|-7.4009|20.8185|2451|6468|P|M|1|444484
MEG|FNMA|Malanje Airport|Malanje|Malanje|AO|MAL|-9.5251|16.3124|3868|7283|P|M|1|639220
NBJ|FNBJ|Dr. Antonio Agostinho Neto International Airport|Luanda|Luanda|AO|LUA|-9.0507|13.4991|550|13123|P|L|1|13362661
SDD|FNUB|Lubango Mukanka International Airport|Lubango|Lubango|AO|HUI|-14.9248|13.5767|5778|10335|P|M|1|621251
SPP|FNME|Menongue Airport|Menongue|Menongue|AO|CCU|-14.6576|17.7198|4469|11483|P|M|1|266178
SVP|FNKU|Kuito Airport|Kuito|Kuito|AO|BIE|-12.4046|16.9474|5618|8202|P|M|0|492986
VHC|FNSA|Saurimo Airport|Saurimo|Saurimo|AO|LSU|-9.6891|20.4319|3584|11155|P|M|0|393000
VPE|FNGI|Ngjiva Pereira Airport|Ngiva|Ngiva|AO|CNN|-17.0435|15.6838|3566|10640|P|M|1|152429
BOY|DFOO|Bobo Dioulasso Airport|Bobo Dioulasso|Bobo Dioulasso|BF|HOU|11.1601|-4.3310|1511|10826|P|L|1|1736452
OUA|DFFD|Ouagadougou Thomas Sankara International Airport|Ouagadougou|Ouagadougou|BF|KAD|12.3532|-1.5124|1037|9843|P|L|1|3957011
BJM|HBBA|Bujumbura Melchior Ndadaye International Airport|Bujumbura|Bujumbura|BI|BM|-3.3240|29.3185|2582|11811|P|L|1|1685450
GBE|FBSK|Sir Seretse Khama International Airport|Gaborone|Gaborone|BW|GA|-24.5552|25.9182|3299|13123|P|L|1|903581
MUB|FBMN|Maun International Airport|Maun|Maun|BW|NW|-19.9705|23.4314|3093|6562|P|L|1|102264
SXN|FBSN|Sua Pan Airport|Sowa|Sowa|BW|ST|-20.5534|26.1158|2985|5381|P|M|0|15021
BDT|FZFD|Gbadolite Airport|Gbadolite|Gbadolite|CD|NU|4.2527|20.9753|1509|10499|P|M|1|113602
BNB|FZGN|Boende Airport|Boende|Boende|CD|TU|-0.2867|20.8836|1168|3000|G|S|1|50794
BUX|FZKA|Bunia Airport|Bunia|Bunia|CD|IT|1.5657|30.2207|4045|8202|P|M|1|509856
BZU|FZKJ|Buta Zega Airport|Buta|Buta|CD|BU|2.8181|24.7940|1378|6890|P|M|0|80751
FBM|FZQA|Lubumbashi International Airport|Lubumbashi|Lubumbashi|CD|HK|-11.5915|27.5308|4295|10623|P|L|1|3259916
FIH|FZAA|Ndjili International Airport|Kinshasa|Kinshasa|CD|KN|-4.3857|15.4446|1027|13123|P|L|1|6277556
FKI|FZIC|Bangoka International Airport|Kisangani|Kisangani|CD|TO|0.4816|25.3380|1417|11483|P|L|1|1664226
FMI|FZRF|Kalemie Airport|Kalemie|Kalemie|CD|TA|-5.8756|29.2500|2569|5741|P|M|1|160961
IRP|FZJH|Matari Airport|Isiro|Isiro|CD|HU|2.8276|27.5883|2438|8202|P|M|1|272782
KKW|FZCA|Kikwit Airport|Kikwit|Kikwit|CD|KL|-5.0358|18.7856|1572|5151|P|M|1|678642
KMN|FZSB|Kamina City Airport|Kamina|Kamina|CD|HL|-8.7289|24.9914|3475|4823|G|S|1|200184
KND|FZOA|Kindu Airport|Kindu|Kindu|CD|MA|-2.9192|25.9154|1630|7218|P|M|1|234651
MDK|FZEA|Mbandaka Airport|Mbandaka|Mbandaka|CD|EQ|0.0226|18.2887|1040|7223|P|M|1|534659
MJM|FZWA|Mbuji Mayi Airport|Mbuji Mayi|Mbuji Mayi|CD|KE|-6.1212|23.5690|2221|6558|P|M|1|2424262
BBT|FEFT|Berberati Airport|Berberati|Berberati|CF|HS|4.2216|15.7864|1929|5446|P|M|0|277716
BGF|FEFF|Bangui M'Poko International Airport|Bangui|Bangui|CF|MP|4.3985|18.5188|1208|8530|P|L|1|1652920
OLL|FCOD|Oyo Ollombo Airport|Oyo|Oyo|CG|14|-1.2267|15.9100|1073|10827|P|M|0|62266
PNR|FCPP|Antonio Agostinho-Neto International Airport|Pointe Noire|Pointe Noire|CG|5|-4.8160|11.8866|55|8530|P|L|1|1266163
ABJ|DIAP|Felix-Houphouet-Boigny International Airport|Abidjan|Abidjan|CI|AB|5.2614|-3.9263|21|9843|P|L|1|11355541
ASK|DIYO|Yamoussoukro International Airport|Yamoussoukro|Yamoussoukro|CI|YM|6.9032|-5.3656|699|9843|P|L|0|6010848
SPY|DISP|San Pedro Airport|San-Pedro|San-Pedro|CI|BS|4.7467|-6.6608|26|6234|P|M|1|1249892
BPC|FKKV|Bamenda Airport|Bamenda|Bamenda|CM|NW|6.0392|10.1226|4065|8202|P|M|0|815305
GOU|FKKR|Garoua International Airport|Garoua|Garoua|CM|NO|9.3348|13.3721|794|11032|P|L|1|642962
NSI|FKYS|Yaounde Nsimalen International Airport|Yaounde|Yaounde|CM|CE|3.7226|11.5533|2278|11155|P|L|1|1929518
RAI|GVNP|Nelson Mandela International Airport|Praia|Praia|CV|S|14.9411|-23.4847|230|6890|P|L|1|427154
VXE|GVSV|Cesaria Evora International Airport|Sao Pedro|Sao Pedro|CV|B|16.8334|-25.0553|66|6561|P|L|1|172843
ASA|HHSB|Assab International Airport|Assab|Assab|ER|DK|13.0718|42.6450|46|11531|P|M|0|38894
ASM|HHAS|Asmara International Airport|Asmara|Asmara|ER|SK|15.2919|38.9107|7661|9842|P|M|1|707809
ABK|HAKD|Kebri Dahar Airport|Kebri Dahar|Kebri Dahar|ET|SO|6.7326|44.2413|1800|8202|P|M|1|45900
ADD|HAAB|Addis Ababa Bole International Airport|Addis Ababa|Addis Ababa|ET|AA|8.9779|38.7993|7630|12467|P|L|1|6057073
BJR|HABD|Bahir Dar Airport|Bahir Dar|Bahir Dar|ET|AM|11.6081|37.3216|5978|9842|P|M|1|855752
DSE|HADC|Kombolcha Airport|Dessie|Dessie|ET|AM|11.1098|39.7259|6120|3000|G|S|1|493100
GMB|HAGM|Gambela Airport|Gambela|Gambela|ET|GA|8.1288|34.5631|1614|8248|P|M|1|112310
JIM|HAJM|Jimma Airport|Jimma|Jimma|ET|OR|7.6661|36.8166|5500|10236|P|M|1|406894
MJL|FOGM|Mouilla Ville Airport|Mouila|Mouila|GA|4|-1.8451|11.0567|295|5891|P|M|0|73956
MKU|FOOK|Makokou Airport|Makokou|Makokou|GA|6|0.5792|12.8909|1726|5892|P|M|1|28887
MVB|FOON|M'Vengue El Hadj Omar Bongo Ondimba International Airport|Franceville|Franceville|GA|2|-1.6562|13.4380|1450|10105|P|M|1|236550
ACC|DGAA|Kotoka International Airport|Accra|Accra|GH|AA|5.6052|-0.1668|205|11165|P|L|1|4499799
NYI|DGSN|Sunyani Airport|Sunyani|Sunyani|GH|BO|7.3618|-2.3288|1014|4594|P|M|1|619426
CKY|GUCY|Ahmed Sekou Toure International Airport|Conakry|Conakry|GN|C|9.5769|-13.6120|72|10826|P|L|1|4614185
OCS|FGCO|Corisco International Airport|Corisco Island|Corisco Island|GQ|LI|0.9109|9.3303|55|10220|P|L|1|137862
SSG|FGSL|Malabo International Airport|Malabo|Malabo|GQ|BN|3.7553|8.7087|76|9647|P|L|1|441959
OXB|GGOV|Osvaldo Vieira International Airport|Bissau|Bissau|GW|BS|11.8943|-15.6536|129|10499|P|L|1|1244339
EDL|HKEL|Eldoret International Airport|Eldoret|Eldoret|KE|27|0.4045|35.2389|6941|11480|P|L|1|2190737
LOK|HKLO|Lodwar Airport|Lodwar|Lodwar|KE|23|3.1220|35.6087|1715|3281|P|M|0|95646
MYD|HKML|Malindi International Airport|Malindi|Malindi|KE|03|-3.2293|40.1017|80|4600|G|M|1|179809
NBO|HKJK|Jomo Kenyatta International Airport|Nairobi|Nairobi|KE|47|-1.3189|36.9282|5330|13507|P|L|1|8659933
WJR|HKWJ|Wajir Airport|Wajir|Wajir|KE|08|1.7332|40.0916|770|9193|P|M|1|101197
HAH|FMCH|Prince Said Ibrahim International Airport|Moroni|Moroni|KM|G|-11.5337|43.2719|93|9514|P|L|1|203161
ROB|GLRB|Roberts International Airport|Monrovia|Monrovia|LR|MG|6.2338|-10.3623|31|11000|P|L|1|1830044
FTU|FMSD|Tolanaro Airport|Tolanaro|Tolanaro|MG|U|-25.0381|46.9561|29|5280|P|M|1|189228
MJN|FMNM|Amborovy Airport|Mahajanga|Mahajanga|MG|M|-15.6668|46.3512|87|7218|P|L|1|416636
MOQ|FMMV|Morondava Airport|Morondava|Morondava|MG|U|-20.2847|44.3176|30|4921|P|M|1|80571
NOS|FMNN|Nosy Be International Airport|Nosy Be|Nosy Be|MG|D|-13.3121|48.3148|36|7185|P|L|1|286944
TLE|FMST|Toliara Airport|Toliara|Toliara|MG|U|-23.3834|43.7285|29|6562|P|M|1|219850
TNR|FMMI|Ivato International Airport|Antananarivo|Antananarivo|MG|T|-18.7969|47.4788|4198|10171|P|L|1|2405954
WFI|FMSF|Fianarantsoa Airport|Fianarantsoa|Fianarantsoa|MG|F|-21.4416|47.1117|3658|4101|P|M|0|314992
WMN|FMNR|Maroantsetra Airport|Maroantsetra|Maroantsetra|MG|A|-15.4377|49.6891|9|4265|P|M|1|77519
WTA|FMMU|Tambohorano Airport|Tambohorano|Tambohorano|MG|M|-17.4761|43.9728|23|3000|G|S|1|150
BKO|GABS|Modibo Keita International Airport|Bamako|Bamako|ML|2|12.5335|-7.9499|1247|10498|P|L|1|5073508
GAQ|GAGO|Gao International Airport|Gao|Gao|ML|7|16.2485|-0.0054|870|8202|P|M|1|178481
KYS|GAKD|Kayes Dag Dag Airport|Kayes|Kayes|ML|1|14.4825|-11.3993|164|8858|P|M|1|202350
MZI|GAMB|Mopti Airport|Sevare|Sevare|ML|5|14.5128|-4.0796|906|8340|P|M|1|283295
TOM|GATB|Tombouktou Airport|Timbuktu|Timbuktu|ML|7|16.7305|-3.0076|863|6923|P|L|1|141857
ATR|GQPA|Atar International Airport|Atar|Atar|MR|07|20.5058|-13.0437|734|9855|P|M|0|44031
NDB|GQPP|Nouadhibou International Airport|Nouadhibou|Nouadhibou|MR|08|20.9324|-17.0302|24|7961|P|L|1|160326
NKC|GQNO|NouakchottOumtounsy International Airport|Nouakchott|Nouakchott|MR|NKC|18.3100|-15.9697|9|11155|P|L|1|1367691
OUZ|GQPZ|Tazadit Airport|Zouerate|Zouerate|MR|11|22.7573|-12.4822|1119|8202|P|M|1|59775
MRU|FIMP|Sir Seewoosagur Ramgoolam International Airport|Plaine Magnien|Plaine Magnien|MU|GP|-20.4302|57.6836|186|11056|P|L|1|1240022
RRG|FIMR|Sir Charles Gaetan Duval Airport|Port Mathurin|Port Mathurin|MU|RO|-19.7567|63.3593|95|4223|P|M|1|10850
LLW|FWKI|Kamuzu International Airport|Lumbadzi|Lumbadzi|MW|LI|-13.7894|33.7810|4035|11614|P|L|1|1521479
ZZU|FWUU|Mzuzu Airport|Mzuzu|Mzuzu|MW|MZ|-11.4447|34.0118|4115|4291|P|M|0|342427
APL|FQNP|Nampula Airport|Nampula|Nampula|MZ|N|-15.1056|39.2818|1444|6562|P|L|1|1078867
BEW|FQBR|Beira International Airport|Beira|Beira|MZ|S|-19.7964|34.9076|33|7874|P|L|1|809534
INH|FQIN|Inhambane Airport|Inhambane|Inhambane|MZ|I|-23.8764|35.4085|30|4921|P|M|1|276502
MPM|FQMA|Maputo Airport|Maputo|Maputo|MZ|MPM|-25.9208|32.5726|145|12008|P|L|1|2854639
POL|FQPB|Pemba Airport|Pemba|Pemba|MZ|P|-12.9933|40.5249|331|5905|P|M|1|238633
TET|FQTT|Tete Airport|Tete|Tete|MZ|T|-16.1048|33.6402|525|8225|P|L|1|439948
UEL|FQQL|Quelimane Airport|Quelimane|Quelimane|MZ|Q|-17.8555|36.8691|36|5905|P|M|1|372489
FYTF|FYTF|Twyfelfontein Airport|Twyfelfontein|Twyfelfontein|NA|KU|-20.5442|14.3588|1772|6550|P|M|1|12676
KMP|FYKT|Keetmanshoop Airport|Keetmanshoop|Keetmanshoop|NA|KA|-26.5398|18.1114|3506|7598|P|M|0|25978
NDU|FYRU|Rundu Airport|Rundu|Rundu|NA|KE|-17.9565|19.7194|3627|11004|P|M|1|83921
TSB|FYTM|Tsumeb Airport|Tsumeb|Tsumeb|NA|OT|-19.2621|17.7325|4353|4823|P|M|0|31351
WDH|FYWH|Hosea Kutako International Airport|Windhoek|Windhoek|NA|KH|-22.4799|17.4709|5640|15010|P|L|1|482536
WVB|FYWB|Walvis Bay International Airport|Walvis Bay|Walvis Bay|NA|ER|-22.9793|14.6471|299|11483|P|L|1|133860
AJY|DRZA|Mano Dayak International Airport|Agadez|Agadez|NE|1|16.9660|8.0001|1657|9843|P|M|0|251063
NIM|DRRN|Diori Hamani International Airport|Niamey|Niamey|NE|8|13.4815|2.1836|732|10499|G|L|1|1569883
ABB|DNAS|Asaba International Airport|Asaba|Asaba|NG|DE|6.2042|6.6653|305|11155|P|L|1|3522965
ABV|DNAA|Nnamdi Azikiwe International Airport|Abuja|Abuja|NG|FC|9.0068|7.2632|1123|11842|P|L|1|3794242
GMO|DNGO|Gombe Lawanti International Airport|Gombe|Gombe|NG|GO|10.2989|10.9000|1590|10827|P|M|1|803557
ILR|DNIL|General Tunde Idiagbon International Airport|Ilorin|Ilorin|NG|KW|8.4402|4.4939|1126|10169|P|L|1|5968177
KAN|DNKN|Mallam Aminu Kano International Airport|Kano|Kano|NG|KN|12.0456|8.5236|1562|10831|P|L|1|5551883
LOS|DNMM|Murtala Muhammed International Airport|Lagos|Lagos|NG|LA|6.5774|3.3212|135|12794|P|L|1|21270055
MIU|DNMA|Maiduguri International Airport|Maiduguri|Maiduguri|NG|BO|11.8542|13.0807|1099|9846|P|L|1|1555986
SKO|DNSO|Sadiq Abubakar III International Airport|Sokoto|Sokoto|NG|SO|12.9157|5.2075|1010|9844|P|L|1|1323501
ZSE|FMEP|Saint-Pierre Pierrefonds Airport|Saint-Pierre|Saint-Pierre|RE|SR|-21.3194|55.4225|59|7000|P|L|1|445441
FSAL|FSAL|Alphonse Airport|Alphonse Island|Alphonse Island|SC|26|-7.0048|52.7262|10|3983|P|S|1|150
SEZ|FSIA|Seychelles International Airport|Victoria|Victoria, SC|SC|20|-4.6743|55.5218|10|9800|P|L|1|107483
ASI|FHAW|RAF Ascension Island|Cat Hill|Cat Hill|SH|AC|-7.9702|-14.3927|278|10019|P|M|1|5012
HLE|FHSH|Saint Helena International Airport|Jamestown|Jamestown, SH|SH|SH|-15.9589|-5.6461|1017|6398|P|M|1|3364
WYE|GFYE|Yengema Airport|Yengema|Yengema|SL|E|8.6105|-11.0454|1300|3000|G|M|0|215669
DSS|GOBD|Blaise Diagne International Airport|Dakar|Dakar|SN|DK|14.6709|-17.0728|290|11483|P|L|1|7933110
TUD|GOTT|Tambacounda Airport|Tambacounda|Tambacounda|SN|TC|13.7368|-13.6531|161|6562|P|M|0|357093
BSA|HCMF|Bender Qassim International Airport|Bosaso|Bosaso|SO|BR|11.2752|49.1392|3|7874|P|L|1|100528
GLK|HCMR|Galcaio Airport|Galcaio|Galcaio|SO|MU|6.7808|47.4547|975|9859|P|S|1|61200
HGA|HCMH|Egal International Airport|Hargeisa|Hargeisa|SO|WO|9.5141|44.0835|4471|12139|P|L|1|835134
KMU|HCMK|Kismayo Airport|Kismayo|Kismayo|SO|JH|-0.3774|42.4592|49|12139|P|M|0|277122
MGQ|HCMM|Aden Adde International Airport|Mogadishu|Mogadishu|SO|BN|2.0144|45.3047|29|10446|P|L|1|3017230
JUB|HJJJ|Juba International Airport|Juba|Juba|SS|EC|4.8720|31.6011|1513|10171|P|L|1|825350
MAK|HSSM|Malakal International Airport|Malakal|Malakal|SS|NU|9.5587|31.6519|1291|6562|P|M|1|168474
WUU|HSWW|Wau Airport|Wau|Wau|SS|BW|7.7258|27.9750|1529|8202|P|M|1|205384
TMS|FPST|Sao Tome International Airport|Sao Tome|Sao Tome|ST|01|0.3782|6.7122|33|7283|P|L|1|132323
AEH|FTTC|Abeche Airport|Abeche|Abeche|TD|OD|13.8470|20.8443|1788|9186|P|M|0|175023
FYT|FTTY|Faya-Largeau Airport|Faya-Largeau|Faya-Largeau|TD|BO|17.9171|19.1111|771|9186|P|M|0|53356
MQQ|FTTD|Moundou Airport|Moundou|Moundou|TD|LO|8.6285|16.0742|1407|5906|P|M|0|515437
LRL|DXNG|Niamtougou International Airport|Niamtougou|Niamtougou|TG|K|9.7667|1.0909|1515|8202|P|L|0|896551
DOD|HTDO|Dodoma Airport|Dodoma|Dodoma|TZ|03|-6.1706|35.7560|3673|6700|P|M|1|830452
LKY|HTLM|Lake Manyara Airport|Lake Manyara National|Lake Manyara National|TZ|26|-3.3763|35.8183|4150|4003|P|M|0|128308
MBI|HTGW|Songwe Airport|Mbeya|Mbeya|TZ|14|-8.9199|33.2740|4412|10925|P|M|1|1351573
MWZ|HTMW|Mwanza International Airport|Mwanza|Mwanza|TZ|18|-2.4466|32.9360|3763|10212|P|L|1|2705320
MYW|HTMT|Mtwara Airport|Mtwara|Mtwara|TZ|17|-10.3362|40.1820|371|7410|P|M|1|351843
TBO|HTTB|Tabora Airport|Tabora|Tabora|TZ|24|-5.0764|32.8333|3868|6234|P|S|1|356961
ZNZ|HTZA|Abeid Amani Karume International Airport|Zanzibar|Zanzibar|TZ|07|-6.2220|39.2249|54|9915|P|L|1|1448530
EBB|HUEN|Entebbe International Airport|Entebbe|Entebbe|UG|C|0.0424|32.4435|3782|12000|P|L|1|5942608
KHX|UG-0002|Savannah Airstrip|Kihihi|Kihihi|UG|W|-0.7165|29.6997|3600|6004|G|M|1|518166
DZA|FMCZ|Dzaoudzi Pamandzi International Airport|Dzaoudzi|Dzaoudzi|YT|A|-12.8093|45.2818|23|6330|P|L|1|386459
ALJ|FAAB|Alexander Bay Airport|Alexander Bay|Alexander Bay|ZA|NC|-28.5750|16.5333|98|6063|P|M|0|9360
BFN|FABL|Bram Fischer International Airport|Bloemfontein|Bloemfontein|ZA|FS|-29.0927|26.3024|4457|8396|P|L|1|1844334
CPT|FACT|Cape Town International Airport|Cape Town|Cape Town|ZA|WC|-33.9740|18.6043|151|10502|P|L|1|6788797
DUR|FALE|King Shaka International Airport|Durban|Durban|ZA|NL|-29.6144|31.1197|295|12139|P|L|1|4056185
GRJ|FAGG|George Airport|George|George|ZA|WC|-34.0056|22.3789|648|6562|P|L|1|497059
JNB|FAOR|O.R. Tambo International Airport|Johannesburg|Johannesburg|ZA|GT|-26.1401|28.2468|5558|14495|P|L|1|18926202
PLZ|FAPE|Chief Dawid Stuurman International Airport|Gqeberha|Gqeberha|ZA|EC|-33.9897|25.6174|226|7087|P|L|1|1653064
PTG|FAPP|Polokwane International Airport|Polokwane|Polokwane|ZA|LP|-23.8453|29.4586|4076|8400|P|L|1|983689
UTN|FAUP|Upington Airport|Upington|Upington|ZA|NC|-28.4002|21.2636|2782|16076|P|M|1|106254
UTT|FAUT|K. D. Matanzima Airport|Mthatha|Mthatha|ZA|EC|-31.5464|28.6734|2400|8530|P|M|1|263639
VRE|FAVR|Vredendal Airport|Vredendal|Vredendal|ZA|WC|-31.6410|18.5448|330|4265|G|M|0|69012
VRU|FAVB|Vryburg Airport|Vryburg|Vryburg|ZA|NW|-26.9824|24.7288|3920|3937|P|M|0|163765
KAA|FLKS|Kasama Airport|Kasama|Kasama|ZM|05|-10.2102|31.1230|4541|6148|G|S|1|192172
LUN|FLKK|Kenneth Kaunda International Airport|Lusaka|Lusaka|ZM|09|-15.3308|28.4527|3779|12998|P|L|1|3382095
MNR|FLMG|Mongu Airport|Mongu|Mongu|ZM|01|-15.2545|23.1623|3488|4800|G|M|0|140611
BFO|FVCZ|Buffalo Range Airport|Chiredzi|Chiredzi|ZW|MV|-21.0081|31.5786|1421|5785|P|M|0|40100
BUQ|FVJN|Joshua Mqabuko Nkomo International Airport|Bulawayo|Bulawayo|ZW|BU|-20.0163|28.6229|4359|8491|P|L|1|905095
HRE|FVRG|Robert Gabriel Mugabe International Airport|Harare|Harare|ZW|HA|-17.9318|31.0928|4887|15502|P|L|1|2902688
VFA|FVFA|Victoria Falls International Airport|Victoria Falls|Victoria Falls|ZW|MN|-18.0974|25.8369|3490|13123|P|L|1|82907
"""#
}
