// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_SAS {
    static let rows = #"""
CGP|VGEG|Shah Amanat International Airport|Chattogram|Chattogram|BD|B|22.2496|91.8133|12|9646|P|L|1|5764156
DAC|VGHS|Hazrat Shahjalal International Airport|Dhaka|Dhaka|BD|C|23.8433|90.3978|30|11500|P|L|1|20402219
SPD|VGSD|Saidpur Airport|Saidpur|Saidpur|BD|E|25.7592|88.9089|125|6000|P|M|1|1821657
AGX|VOAT|Agatti Airport|Agatti|Agatti|IN|LD|10.8237|72.1760|14|4235|P|M|1|32157
AMD|VAAH|Sardar Vallabh Patel International Airport|Ahmedabad|Ahmedabad|IN|GJ|23.0772|72.6347|189|11499|P|L|1|9439021
ATQ|VIAR|Sri Guru Ram Das Ji International Airport|Amritsar|Amritsar|IN|PB|31.7096|74.7973|756|12000|P|L|1|5710609
BBI|VEBS|Biju Patnaik International Airport|Bhubaneswar|Bhubaneswar|IN|OR|20.2510|85.8147|138|9003|P|L|1|3807461
BEK|VIBY|Bareilly Air Force Station|Bareilly|Bareilly|IN|UP|28.4221|79.4508|580|9000|P|M|1|2229720
BLR|VOBL|Kempegowda International Airport Bengaluru|Bengaluru|Bengaluru|IN|KA|13.1979|77.7063|3000|13123|P|L|1|12463908
BOM|VABB|Chhatrapati Shivaji Maharaj International Airport|Mumbai|Mumbai|IN|MM|19.0887|72.8679|39|11511|P|L|1|17376093
CCU|VECC|Netaji Subhash Chandra Bose International Airport|Kolkata|Kolkata|IN|WB|22.6540|88.4476|16|11919|P|L|1|16292983
COK|VOCI|Cochin International Airport|Kochi|Kochi|IN|KL|10.1510|76.4008|30|11155|P|L|1|8806675
DEL|VIDP|Indira Gandhi International Airport|New Delhi|New Delhi|IN|DL|28.5556|77.0952|777|14534|P|L|1|29191882
GAU|VEGT|Lokpriya Gopinath Bordoloi International Airport|Guwahati|Guwahati|IN|AS|26.1067|91.5852|162|9000|P|L|1|2236873
GOX|VOGA|Manohar International Airport|Mopa|Mopa|IN|GA|15.7443|73.8606|552|11483|P|L|1|1115686
HYD|VOHS|Rajiv Gandhi International Airport|Hyderabad|Hyderabad|IN|TG|17.2313|78.4299|2024|13976|P|L|1|12220944
IDR|VAID|Devi Ahilya Bai Holkar International Airport|Indore|Indore|IN|MP|22.7214|75.8005|1850|9035|G|L|1|5799129
IMF|VEIM|Bir Tikendrajit International Airport|Imphal|Imphal|IN|MN|24.7600|93.8967|2540|9009|P|L|1|1099313
IXC|VICG|Shaheed Bhagat Singh International Airport|Chandigarh|Chandigarh|IN|CH|30.6735|76.7885|1012|12467|P|L|1|5642389
IXE|VOML|Mangaluru International Airport|Mangaluru|Mangaluru|IN|KA|12.9547|74.8868|337|8035|P|L|1|2346959
IXI|VELR|Lilabari North Lakhimpur Airport|Lilabari|Lilabari|IN|AS|27.2957|94.0973|330|7500|P|M|1|187951
IXR|VERC|Birsa Munda Airport|Ranchi|Ranchi|IN|JH|23.3143|85.3217|2148|8855|P|M|1|2607705
IXU|VAAU|Aurangabad Airport|Aurangabad|Aurangabad|IN|MM|19.8629|75.3963|1911|9314|P|M|1|2124513
IXY|VAKE|Kandla Airport|Kandla|Kandla|IN|GJ|23.1127|70.1003|96|4997|P|M|1|487204
IXZ|VOPB|Veer Savarkar International Airport / INS Utkrosh|Port Blair|Port Blair|IN|AN|11.6402|92.7290|13|10795|P|L|1|210216
JAI|VIJP|Jaipur International Airport|Jaipur|Jaipur|IN|RJ|26.8242|75.8122|1263|9177|P|L|1|5913923
JDH|VIJO|Jodhpur Airport|Jodhpur|Jodhpur|IN|RJ|26.2511|73.0489|717|9005|P|M|1|1575689
JLR|VAJB|Jabalpur Airport|Jabalpur|Jabalpur|IN|MP|23.1778|80.0520|1624|6522|P|M|1|1859642
LKO|VILK|Chaudhary Charan Singh International Airport|Lucknow|Lucknow|IN|UP|26.7606|80.8893|410|8996|P|L|1|5899495
MAA|VOMM|Chennai International Airport|Chennai|Chennai|IN|TN|12.9900|80.1693|52|12001|P|L|1|9869286
NAG|VANP|Dr. Babasaheb Ambedkar International Airport|Nagpur|Nagpur|IN|MM|21.0922|79.0472|1033|10500|P|L|1|5946253
PAT|VEPT|Jay Prakash Narayan Airport|Patna|Patna|IN|BR|25.5913|85.0880|170|6410|P|M|1|4155808
RPR|VERP|Swami Vivekananda Airport|Raipur|Raipur|IN|CT|21.1804|81.7388|1041|6414|P|M|1|3003950
SSE|VASL|Solapur Airport|Solapur|Solapur|IN|MM|17.6280|75.9348|1584|6591|P|M|0|1514237
STV|VASU|Surat International Airport|Surat|Surat|IN|GJ|21.1155|72.7433|16|9530|P|L|1|6851593
TRV|VOTV|Thiruvananthapuram International Airport|Thiruvananthapuram|Thiruvananthapuram|IN|KL|8.4819|76.9200|15|11148|P|L|1|7378914
TRZ|VOTR|Tiruchirappalli International Airport|Tiruchirappalli|Tiruchirappalli|IN|TN|10.7629|78.7177|288|6115|P|L|1|7979354
VGA|VOBZ|Vijayawada International Airport|Vijayawada|Vijayawada|IN|AP|16.5300|80.8049|82|11023|P|L|1|6061684
VTZ|VOVI|Alluri Sitarama Raju International Airport (Vizag)|Visakhapatnam|Visakhapatnam|IN|AP|17.9715|83.5036|188|9000|G|L|1|4844566
CMB|VCBI|Bandaranaike International Colombo Airport|Colombo|Colombo|LK|1|7.1808|79.8841|30|10991|P|L|1|2107040
DWO|DWO|Diyawanna Oya Seaplane Base|Sri Jayawardenepura|Sri Jayawardenepura|LK|1|6.9066|79.9090|10|0|W|W|1|575163
GAN|VRMG|Gan International Airport|Gan|Gan|MV|01|-0.6930|73.1526|6|12000|P|L|1|23295
HAQ|VRMH|Hanimaadhoo International Airport|Haa Dhaalu Atoll|Haa Dhaalu Atoll|MV|23|6.7432|73.1671|4|8087|P|L|1|11531
KDO|VRMK|Kadhdhoo Airport|Kadhdhoo|Kadhdhoo|MV|05|1.8592|73.5219|4|4003|P|M|1|5445
MLE|VRMM|Velana International Airport|Male|Male|MV|MLE|4.1918|73.5291|6|11155|P|L|1|119270
IMK|VNST|Simikot Airport|Simikot|Simikot|NP|P6|29.9711|81.8189|9246|3000|G|S|1|1975
JMO|VNJS|Jomsom Airport|Jomsom|Jomsom|NP|P4|28.7804|83.7230|8976|2424|P|S|1|286
LUA|VNLK|Tenzing-Hillary Airport|Lukla|Lukla|NP|P1|27.6868|86.7295|9380|1729|P|M|1|22902
PHH|VNPR|Pokhara International Airport|Pokhara|Pokhara|NP|P4|28.1838|84.0147|2595|8202|P|L|1|856433
RJB|VNRB|Rajbiraj Airport|Rajbiraj|Rajbiraj|NP|P2|26.5101|86.7339|250|3000|G|S|0|72315
SKH|VNSK|Surkhet Airport|Surkhet|Surkhet|NP|P6|28.5860|81.6360|2400|3400|G|S|1|143912
CJL|OPCH|Chitral Airport|Chitral|Chitral|PK|KP|35.8862|71.7999|4920|5741|P|M|1|141992
DBA|OPDB|Dalbandin Airport|Dalbandin|Dalbandin|PK|BA|28.8783|64.3998|2800|3000|G|S|1|14621
ISB|OPIS|Islamabad International Airport|Attock|Attock|PK|PB|33.5490|72.8257|1761|12001|P|L|1|7064911
KDU|OPSD|Skardu International Airport|Skardu|Skardu|PK|GB|35.3387|75.5386|7316|11995|P|L|1|335380
KHI|OPKC|Jinnah International Airport|Karachi|Karachi|PK|SD|24.9065|67.1608|100|11155|P|L|1|12756932
MUX|OPMT|Multan International Airport|Multan|Multan|PK|PB|30.2032|71.4191|403|12353|P|L|1|5955161
SKZ|OPSK|Begum Nusrat Bhutto International Airport Sukkur|Sukkur|Sukkur|PK|SD|27.7220|68.7917|196|9000|P|M|1|2646838
TUK|OPTU|Turbat International Airport|Turbat|Turbat|PK|BA|25.9848|63.0289|498|9022|P|L|1|103475
UET|OPQT|Quetta International Airport|Quetta|Quetta|PK|BA|30.2514|66.9378|5267|12001|P|L|1|1981282
"""#
}
