// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).

enum AirportRows_NRD {
    static let rows = #"""
CPH|EKCH|Copenhagen Kastrup Airport|Copenhagen|Copenhagen|DK|84|55.6179|12.6560|17|11811|P|L|1|3656219
TED|EKTS|Thisted Airport|Thisted|Thisted|DK|81|57.0688|8.7052|23|5249|P|M|0|23636
HEL|EFHK|Helsinki Vantaa Airport|Helsinki|Helsinki|FI|18|60.3184|24.9633|179|11483|P|L|1|3545271
KAO|EFKS|Kuusamo Airport|Kuusamo|Kuusamo|FI|14|65.9876|29.2394|866|8202|P|M|1|22676
KTT|EFKT|Kittila International Airport|Kittila|Kittila|FI|10|67.7010|24.8468|644|8202|P|L|1|18337
KUO|EFKU|Kuopio Airport|Kuopio|Kuopio|FI|15|63.0071|27.7978|323|9186|P|L|1|341559
VAA|EFVA|Vaasa Airport|Vaasa|Vaasa|FI|12|63.0502|21.7625|19|8727|P|L|1|246612
FAE|EKVG|Vagar Airport|Vagar|Vagar|FO|A|62.0633|-7.2758|280|5905|P|L|1|46493
AEY|BIAR|Akureyri International Airport|Akureyri|Akureyri|IS|6|65.6566|-18.0720|6|8858|P|L|1|24168
KEF|BIKF|Keflavik International Airport|Reykjavik|Reykjavik|IS|2|63.9850|-22.6056|171|10056|P|L|1|292290
AES|ENAL|Alesund Airport|Alesund|Alesund|NO|15|62.5604|6.1108|69|7592|P|L|1|103643
BGO|ENBR|Bergen Airport, Flesland|Bergen|Bergen|NO|46|60.2934|5.2181|170|9810|P|L|1|479127
BOO|ENBO|Bod Airport|Bod|Bod|NO|18|67.2692|14.3653|42|9167|P|L|1|54676
BVG|ENBV|Berlevag Airport|Berlevag|Berlevag|NO|56|70.8715|29.0341|42|3372|P|M|1|1166
LYR|ENSB|Svalbard Airport, Longyear|Longyearbyen|Longyearbyen|NO|21|78.2461|15.4656|88|7608|P|M|1|2368
TOS|ENTC|Troms Airport|Troms|Troms|NO|55|69.6833|18.9189|31|8041|P|L|1|72815
TRD|ENVA|Trondheim Airport, Vrnes|Trondheim|Trondheim|NO|50|63.4578|10.9240|56|9052|P|L|1|307824
EKT|ESSU|Eskilstuna Airport|Eskilstuna|Eskilstuna|SE|D|59.3511|16.7084|139|6187|P|M|0|216619
KLR|ESMQ|Kalmar Airport|Kalmar|Kalmar|SE|H|56.6855|16.2876|17|6726|P|M|1|117116
LLA|ESPA|Lulea Airport|Lulea|Lulea|SE|BD|65.5438|22.1220|65|10990|P|L|1|185712
SCR|ESKS|Scandinavian Mountains Airport|Malung-Salen|Malung-Salen|SE|W|61.1651|12.8335|1608|8202|P|L|1|73740
THN|ESGT|Trollhattan-Vanersborg Airport|Trollhattan|Trollhattan|SE|Q|58.3181|12.3450|137|5610|P|M|1|231145
VHM|ESNV|Vilhelmina South Lapland Airport|Vilhelmina|Vilhelmina|SE|AC|64.5791|16.8336|1140|4928|P|M|1|12366
"""#
}
