#!/usr/bin/env python3
"""Writes BitAirlines/Art/AircraftSpriteData.swift from the procedural drawings in aircraft.py.

    python tools/art/build_sprites.py

Each family becomes a list of rows of role characters (see canvas.py), plus the bounding box of its logo cells.
The map icons (top-down, pointing up) are small hand-drawn grids at the bottom of this file.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import aircraft  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'BitAirlines', 'Art', 'AircraftSpriteData.swift')

# Top-down map icons, nose up. 'P' is the livery's primary colour, 'S' the secondary, 'k' outline, 'w' light wing, 'n' engine.
MAP_ICONS = {
    'small': [
        '....k....',
        '...kPk...',
        '...kPk...',
        '.kkkPkkk.',
        'kwwwPwwwk',
        '.kkkPkkk.',
        '...kPk...',
        '..kSSSk..',
        '...kkk...',
    ],
    'medium': [
        '.....k.....',
        '....kPk....',
        '....kPk....',
        '....kPk....',
        '.kkkkPkkkk.',
        'kwwwwPwwwwk',
        '.kknkPknkk.',
        '....kPk....',
        '...kSSSk...',
        '....kkk....',
        '...........',
    ],
    'large': [
        '......k......',
        '.....kPk.....',
        '.....kPk.....',
        '.....kPk.....',
        '.....kPk.....',
        '.kkkkkPkkkkk.',
        'kwwwwwPwwwwwk',
        '.kwnnkPknnwk.',
        '.kkkkkPkkkkk.',
        '.....kPk.....',
        '....kSSSk....',
        '...kSSSSSk...',
        '....kkkkk....',
    ],
    'heavy': [
        '.......k.......',
        '......kPk......',
        '......kPk......',
        '......kPk......',
        '......kPk......',
        '......kPk......',
        '..kkkkkPkkkkk..',
        'kkwwwwwPwwwwwkk',
        'kwwnnwwPwwnnwwk',
        '.kkknkkPkknkkk.',
        '......kPk......',
        '.....kSSSk.....',
        '....kSSSSSk....',
        '.....kkkkk.....',
        '...............',
    ],
}


def swift_rows(rows, indent):
    pad = ' ' * indent
    return ',\n'.join(f'{pad}"{r}"' for r in rows)


def main():
    parts = ['// GENERATED by tools/art/build_sprites.py. Do not edit by hand; change the drawing code and run it again.',
             '// Side views face right. Role characters: . empty, k outline, f fuselage, u belly, c cheat line, g glass, t fin, m fin cap, l logo, w wing, v wing shadow, n engine, d dark.',
             '', 'enum AircraftSpriteData {', '    /// Side-view sprites by family code (see SpriteFamily).', '    static let rows: [String: [String]] = [']
    logo_lines = []
    for name in aircraft.FAMILIES:
        sprite = aircraft.build(name)
        parts.append(f'        "{name}": [')
        parts.append(swift_rows(sprite.lines(), 12))
        parts.append('        ],')
        cells = [(x, y) for y in range(sprite.h) for x in range(sprite.w) if sprite.px[y][x] == 'l']
        if cells:
            xs, ys = [c[0] for c in cells], [c[1] for c in cells]
            logo_lines.append(f'        "{name}": [{min(xs)}, {min(ys)}, {max(xs) - min(xs) + 1}, {max(ys) - min(ys) + 1}],')
        else:
            logo_lines.append(f'        "{name}": [0, 0, 0, 0],')
    parts.append('    ]')
    parts.append('')
    parts.append('    /// Logo rectangle on the tail fin by family: x, y, width, height in sprite pixels (0 width means no room for a logo).')
    parts.append('    static let logoRects: [String: [Int]] = [')
    parts.extend(logo_lines)
    parts.append('    ]')
    parts.append('')
    parts.append('    /// Top-down map icons by size class.')
    parts.append('    static let mapIcons: [String: [String]] = [')
    for name, rows in MAP_ICONS.items():
        parts.append(f'        "{name}": [')
        parts.append(swift_rows(rows, 12))
        parts.append('        ],')
    parts.append('    ]')
    parts.append('}')
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(parts) + '\n')
    print('wrote', OUT)
    for name in aircraft.FAMILIES:
        s = aircraft.build(name)
        print(f'  {name}: {s.w}x{s.h}', end='')
    print()


if __name__ == '__main__':
    main()
