"""Writes the generated Swift data files for CoreCatalog. Everything written here starts with a GENERATED banner."""
import os

BANNER = """// GENERATED by tools/build_data.py. Do not edit by hand; change the script or its inputs and run it again.
// Sources: OurAirports (public domain), GeoNames cities500 (CC BY 4.0, https://www.geonames.org), Natural Earth 50m land (public domain).
"""
GROUP_ORDER = ['NAM', 'CAM', 'CAR', 'SAM', 'EUW', 'EUE', 'NRD', 'RUS', 'MEA', 'NAF', 'CAS', 'SAS', 'EAS', 'SEA', 'OCE', 'SSA']


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def _literal(name, lines, extra=''):
    return f'{BANNER}\nenum {name} {{\n{extra}    static let rows = #"""\n' + '\n'.join(lines) + '\n"""#\n}\n'


def airport_row(a):
    return '|'.join([
        a['code'], a['icao'], a['name'], a['city'], a['cc'], a['region'],
        f"{a['lat']:.4f}", f"{a['lon']:.4f}", str(a['elev']), str(a['rwy']), a['surf'], a['kind'], str(a['sched']), str(a['pop']),
    ])


def emit(out_dir, airports, country_table, mask_rows, mask_size):
    data_dir = os.path.join(out_dir, 'Data')
    groups = {g: [] for g in GROUP_ORDER}
    for a in sorted(airports, key=lambda a: (a['cc'], a['code'])):
        groups[country_table[a['cc']][1]].append(airport_row(a))
    for g in GROUP_ORDER:
        _write(os.path.join(data_dir, f'AirportRows_{g}.swift'), _literal(f'AirportRows_{g}', groups[g]))
    names = ', '.join(f'AirportRows_{g}.rows' for g in GROUP_ORDER)
    _write(os.path.join(data_dir, 'AirportRows.swift'), f'{BANNER}\nenum AirportRows {{\n    static let groups: [String] = [{names}]\n}}\n')

    country_lines = [f'{iso}|{name}|{group}|{wealth}' for iso, (name, group, wealth) in sorted(country_table.items())]
    _write(os.path.join(data_dir, 'CountryRows.swift'), _literal('CountryRows', country_lines))

    width, height = mask_size
    extra = f'    static let width = {width}\n    static let height = {height}\n'
    _write(os.path.join(data_dir, 'LandMaskRows.swift'), _literal('LandMaskRows', mask_rows, extra))
    return {g: len(v) for g, v in groups.items()}
