#!/usr/bin/env python3
"""Recolours the Lontra Industries logo (BitAirlines/DesignSystem/LogoSpriteData.swift) into the game's night-sky palette.

    python tools/recolor_logo.py            # rewrites the palette block in LogoSpriteData.swift
    python tools/recolor_logo.py --preview  # also writes before/after PNGs next to the temp folder

The otter's original colours are kept below, so the script can be run again after changing RAMP. Each colour is mapped by how light it is
onto a ramp of the game's colours (Theme.swift), so the shading survives; the nose keeps one warm accent.
"""
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
FILE = os.path.join(ROOT, 'BitAirlines', 'DesignSystem', 'LogoSpriteData.swift')

# The original warm palette from Ring Legacy's studio logo.
ORIGINAL = {
    'a': 0xE9992B, 'b': 0x100905, 'c': 0xF6E6D0, 'd': 0x695E4F, 'e': 0x3A261B, 'f': 0xF6C770, 'g': 0xD4A46A, 'h': 0xBA833D,
    'i': 0xCABFB0, 'j': 0x271B14, 'k': 0xEE7D5F, 'l': 0xF8DBA7, 'm': 0x714713, 'n': 0x92632A, 'o': 0x503519, 'p': 0xA08C70,
}
# Lightness (0 dark, 1 light) to a game colour: ink navy, deep navy, accent dark, accent sky, ice, near white.
RAMP = [(0.00, 0x0B1020), (0.12, 0x1E2846), (0.36, 0x1F6FA0), (0.60, 0x4FB6F0), (0.82, 0xA8DCF8), (1.00, 0xEEF2FA)]
ACCENTS = {'k': 0xFFD166}        # the nose: Theme.gold


def lightness(rgb):
    r, g, b = (rgb >> 16) & 255, (rgb >> 8) & 255, rgb & 255
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255.0


def ramp(t):
    for (t0, c0), (t1, c1) in zip(RAMP, RAMP[1:]):
        if t <= t1:
            f = (t - t0) / (t1 - t0) if t1 > t0 else 0
            parts = [round(((c0 >> s) & 255) * (1 - f) + ((c1 >> s) & 255) * f) for s in (16, 8, 0)]
            return (parts[0] << 16) | (parts[1] << 8) | parts[2]
    return RAMP[-1][1]


def recoloured():
    return {k: ACCENTS.get(k, ramp(lightness(v))) for k, v in ORIGINAL.items()}


def preview(palette):
    from PIL import Image
    text = open(FILE, encoding='utf-8').read()
    rows = re.findall(r'^\s+"([a-p.]+)",?$', text, re.M)
    out = []
    for pal in (ORIGINAL, palette):
        img = Image.new('RGB', (len(rows[0]), len(rows)), (0x0B, 0x10, 0x20))
        px = img.load()
        for y, row in enumerate(rows):
            for x, ch in enumerate(row):
                if ch != '.':
                    c = pal[ch]
                    px[x, y] = ((c >> 16) & 255, (c >> 8) & 255, c & 255)
        out.append(img.resize((img.width * 3, int(img.height * 3 * 1.25)), Image.NEAREST))
    sheet = Image.new('RGB', (out[0].width, out[0].height * 2 + 10), (40, 40, 40))
    sheet.paste(out[0], (0, 0))
    sheet.paste(out[1], (0, out[0].height + 10))
    path = os.path.join(os.environ.get('TEMP', '.'), 'logo_before_after.png')
    sheet.save(path)
    print(path)


def main():
    palette = recoloured()
    if '--preview' in sys.argv:
        preview(palette)
        return
    text = open(FILE, encoding='utf-8').read()
    block = 'static let studioPalette: [Character: UInt32] = [\n' + ''.join(f'        "{k}": 0x{v:06X},\n' for k, v in sorted(palette.items())) + '    ]'
    text = re.sub(r'static let studioPalette: \[Character: UInt32\] = \[.*?\n    \]', block, text, flags=re.S)
    text = text.replace('// Generated by tools/logo_to_pixels.swift from the Lontra Industries pixel-art logo. Do not edit by hand.',
                        '// The Lontra Industries pixel-art logo. The shapes come from Ring Legacy; the colours are recoloured into this game\'s palette by tools/recolor_logo.py.')
    with open(FILE, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('recoloured', len(palette), 'colours')


if __name__ == '__main__':
    main()
