// The Lontra Industries pixel-art logo. The shapes come from Ring Legacy; the colours are recoloured into this game's palette by tools/recolor_logo.py.
// The source art has slightly tall pixels (about 1.3 high for every 1 wide); the sprite is sampled at half a source pixel, so draw it with aspect 1.25.

extension LogoSprite {
    static let studioPalette: [Character: UInt32] = [
        "a": 0x5DBCF1,
        "b": 0x11182D,
        "c": 0xCBE7F9,
        "d": 0x2273A5,
        "e": 0x1E3556,
        "f": 0x9ED8F7,
        "g": 0x6AC2F2,
        "h": 0x43A4DC,
        "i": 0x8DD1F6,
        "j": 0x1D2744,
        "k": 0xFFD166,
        "l": 0xBBE2F9,
        "m": 0x1F5D89,
        "n": 0x297EB1,
        "o": 0x1E466C,
        "p": 0x47AAE2,
    ]

    static let studioRows: [String] = [
        ".........................................................................bbbbbbbbbbbbb.................................................................................",
        ".................................................................bbbbbbbbbbbbbbbbbbbbbbbb..............................................................................",
        ".................................................................bbbbbbbbbllllllllllbbbbb..............................................................................",
        "..........................................................bbbbbbbbbllllllllllaaaaaaallllbbbb...........................................................................",
        "........................................................bbbbbbbbbbbllllllllllaaaaaaallllbbbbbbbb.......................................................................",
        ".....................................................bbbbbbllllllllllaaaaaaaaaaaaaaaaaafflllbbbbb......................................................................",
        "....................................................bbbbbbbllaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaabbbbbb....................................................................",
        "..................................................bbbbbfaaalaaaaaaaaaaaaaaaaaaaaaaaabbbbbaaaaabbbbbb...................................................................",
        ".................................................bbbbblllaaaaaaaaaaaaaaaaaaaaaaaaaaabbaaaaaaaabbhabbb..................................................................",
        ".................................................bbbpfaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaaaabbb..................................................................",
        "..............................................bbbbbbplaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbaaaaaabbb..................................................................",
        ".............................................bbbbbblllaaaaaaaaaaaaabbbbjaaaaaaaaaaaaaaebccbbbaaabbbbb..................................................................",
        "...........................................bbbbaalllaaaaaaaaaaaaambgnnnaaaaaaaaaaaaaaabbbbbbbaaabbbb...................................................................",
        "..........................................bbbbbaallaaaaaaaaaaaaaabbaaaaaaaaaaaaaaaaaaabbbbbbbaaabbbb...................................................................",
        "..........................................bbbaahbbaaaaaaaaaaaaabbaaaabbbbaaaaaaaaaaaaaagbbbbbaaaaabbbbbbbbbbbbb........................................................",
        "..........................................bbbaabbbaaaaaaaaaaaaabbaaaebcccbaaaaaaaaaaaaaabbbbaaaaaahbbbbbbbbbbbb........................................................",
        "..........................................bbbaabbbbbaaaaaaaaaaaaaaabbbcccbaaaaaaaaabbaababbmacilhabbb..................................................................",
        "..........................................bbbaabbbbbaaaaaaaaaaaaaaabbbbbbbaaaaaaaaabbbbbblccccbbbbbbb..................................................................",
        "..........................................bbbaaaabbaaaaaaaaaaaaaaaabbbbbbbaaaaabbbomooeebbcccccccccjbbbbbbbbb..........................................................",
        "..........................................bbbbaaabbaaaaaaaaaaaaaaaabbbbbbbaaaabbboeoooeebbcccccccccbbbbbbbbbb..........................................................",
        "............................................bbbaamaaaaaaaaaaaaaaaaaaabbbbaaaagbbeeeeeeeebbcccccbbbbbb........bb........................................................",
        "............................................bbbboaaaaaaaaaaccccccccccaaaacccccbbbbeeeeebbccccccccccbbbbbbbb....bb......................................................",
        ".............................................bbbbaaaaaaaaccccccccbbbbbbcccccccbbbbbbbbbbcccccccccccbbbbbbbb....bb......................................................",
        "...............................................bbemaaaaagcccccccbbbbbbbbbiccccccbbbbbbblcccccbbbbbbbb......bb..........................................................",
        "...............................................bbjeaaaaagcccccjbbcccccdbbbccccccccccibbbbbbbbbdccbbbb........bb........................................................",
        "...............................................bbjeaaaaaaaacibbccccbbbbcccccccccccccibbbjbbbbcclpbbbbbb......bb........................................................",
        "...............................................bbeeaaaaaaaaciblccccbbbbccbbccccccccbbbbkkjbbbccbbbbbabbbb..............................................................",
        "...............................................bbjeaaaaaaaaccccccbbccccccbbbccccccbbkkbkkkbbbccbbbbaabbbbb.............................................................",
        "...............................................bbeeeaaaaaaaccccccbbccccbbccbbbbbbbbbkkkkkkbbbbbbbaabbaajbbb............................................................",
        "...............................................bbeeeaaaaaaaccccbbccccbbcccccbbbbbbbbkkkkkkbbbbbaaaabbaaaabbbb..........................................................",
        "...............................................bbjeaaaaaaaaaaaabbccccbbcccccccccclbbkkkkkkbbbaaaabbbbbbaabbbbb.........................................................",
        "...............................................bbeeaaaaaaaaaaaabbccccbjccccccccclcbbbkkkkbbbbaaaabbbbbbaaaabbb.........................................................",
        "...............................................bbeeejaaaaaaaaaaaaccccccccccccjejllllbbbbbbbaaabbbaabbhaabbaagbbb...bbbbb...............................................",
        "...............................................bbeeemaaaaaaaaaaaacccccccccccccejlllllbbbbbbaabbbbbaaaagabbgaanbbbbbbbdbbb..............................................",
        "...............................................bbbbeaaaaaaaaaaaaacccccccccccccccoobbbbbbbaaabbbbbbjaaabbbbbbaaabbbbbcccbb..............................................",
        ".................................................bbeeoaaaaaaaaaaaaacccccccccccccccbpgppbbbbaambbbbaaaaabbbbaaaaaabbccccbbbbbbb.........................................",
        ".................................................bbeeeoaaaaaaaaaaaacccccccccccccccggggggbbbeaabbbaabbaaabbnaajhjabbccllbbbbbbbb........................................",
        ".................................................bbbbeoaaaaaaaaaaaacccccccccccccccccggggggbbbaaaabbbbbbaaaaaabbbbbbbbbbbccclpbb........................................",
        ".................................................bbbbeeeaaaaaaaaaaacccccccccccccccccccggggbbbbaaabbbbbbaagabbbbccccbbbbccccccbb........................................",
        ".................................................bbeoeeeaaaaaaaaaaaaacccccccccccccccccggggggbbbhaaabbaaaabbbbbcccccbbbbccccccbb........................................",
        ".................................................bbhaeeeaaaaaaaaaaaaacccccccccccccccccccggggbbbbbaabbgaabbbbbbdcccccbbbbcccbbbb........................................",
        ".................................................bbbaeeeaaaaaaaaaaaaacccccccccccccccccccggggggbbbbbaaaajbbbcccbbocccaabbdbdbbb.........................................",
        "...............................................bbbbeeeaaaaaaaaaaaaaaaaacccccccccccccccccgggggggjbbbaabbbbbccccioclgbbaaabbbbbbb........................................",
        "...............................................bbbaojnaaaaaaaaaaaaaaaaaafcccccccccccccccggggggbbbbbbbbbbbbccccccclbbbbaaebbaabb........................................",
        "...............................................bbbeehaaaaaaaaaaaaaaaaaaaacccccccccccccccgggggbbbbbbbbbbbbbiicccllbbbbbaaabbaabb........................................",
        "...............................................bbeeeeaaaaaaaaaaaaaaaaaaaaaaccccccccccclgggggbbbaaaabbbbbbbbbllloaaabbbbbaaaahbb........................................",
        ".............................................bbbbeeaaaaaaaaaaaaaaaaaaaabbnlccccccccccclgggbjbbblaaabbbbbbclccffbbaabbbbbaaabbbb........................................",
        ".............................................bbeeaaaaaaaaaaaaaaaaaaaaaabbbbbbccccccccclgbbbbbcllaaaaabbcccllabbbbbaabbaaabbbbb.........................................",
        ".............................................bbeeaaaaaaaaaaaaaaaaaaalllcccbbbbbjcbbjpbbbbbcclllaaaaaabbbcllbbbbbbbbaaaabbbbbb..........................................",
        ".............................................bbeeaaaaaaaaaaaaaaaaaaalllccllbbbbbbbbbbbbbbbllllaaaaaaabbbaaabbbbbbbbaaaabbbbb...........................................",
        "...........................................bbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaalcclbbbbbbllllllaaaaaaaaaabbbbbbaabbbbaaaabbbb..............................................",
        ".........................................bbbbjaaaaaaaaaaaaaaaaaaaaaaaaaaaaaacllbccbicllafaaaaaaaaaaaabbbbbbaaabbbaaabbbbb..............................................",
        ".........................................bbbeaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaaalllllllllaaaaaaaaaaaaabbbbbebbbaaaaaaabbbbb...............................................",
        ".........................................bbjeaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbeebbbbbaaabbbbb.................................................",
        ".......................................bbbbaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbjeehabbbaaabbbb..................................................",
        ".......................................bbeellaaaaaaaaoeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaajbbbbbeeeaambbbbbbb....................................................",
        ".......................................bbeellaaaaaaaaeeeeeoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbeeeeejabbbbbbbb....................................................",
        ".....................................bbbblllaaaaaaaaaaeeeeeeoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbeeeeejabbb.........................................................",
        ".....................................bbbellaaaaaaaaaaaneeeeeoaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbggeeejaaabbb.........................................................",
        ".....................................bbnlllaaaaaaaaaaajeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaebbbbjccceeeeaabbbb.........................................................",
        "...................................bbbbllaaaaaaaaaaaaaaaeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaahbbbbbccccceeaaabbbbb.........................................................",
        "..................................bbbbhllaaaaaaaaaaaaoaaeeeeebbeeaaaaaaaaaaaaaaaaaaaaaaaabbbbccccccceeaaagbb...........................................................",
        ".................................bbbbllllaaaaaaaaaaaaeaaeeeeebbeeaaaaaaaaaaaaaaaaaaaaamjbbbbbbcccccleeaaaobb...........................................................",
        ".................................bbbellaaaaaaaaaaaaaheeeeeeggghbbbbejaaaaaaaaaaaaaoeejbbbbbccccccceeeeaabbbb...........................................................",
        ".................................bbbellaaaaaaaaaaaaaaeeeeeeggggbbbbbbbbbaneaaaaeemeeebbbcccccccccceeebbbbbb............................................................",
        "...............................bbbbjlllaaaaaaaaaaaaaaaheeeeggggggccbbbbbbeeaaaaeeeebbbbblcccccccccoeebbbb..............................................................",
        "..............................bbbbeglaaaaaaaaaaaaaaaaaoeeggggggggcccccdbbeeeeeeebbbbbcccccccccccbbbbbbb................................................................",
        "..............................bbbblllaaaaaaaaaaaaaaaheeeeggggggggccccccbbppoeeeejbbbbccccccccccccbbbbbb................................................................",
        "..............................bbbllllaaaaaaaaaaaaaaaheeeeggggggcccccccccccccccccccccccccccccccccbbbb...................................................................",
        "..............................bbedlaaaaaaaaaaaaaaaaaaeeeeggggggccccccccccccccccccccccccccccccggbbbbb...................................................................",
        "..............................bbedlaaaaaaaaaaaaaaaaaoeeeeeeggggccccccccccccccccccccccccclggggggobbbb...................................................................",
        "..............................bbellaaaaaaaaaaaaaaaaeeeeeeeeggggcccccccccccccccccccccccccgggggggabbbbbb.................................................................",
        "...........................bbbbbejlaaaaaaaaaaaaaaameeeeeeeeggggggccccccccccccccccccccccccccccgggbbbbbb.................................................................",
        "...........................bbbejaalaaaaaaaaaaaaaaameeeeeeeeegggggccccccccccccccccccccccccccccccggaaabbbb...............................................................",
        "...........................bbbehaaaaaaaaaaaaaaaaaaaeeeeeeeeeeggggcccccccccccccccccccccccccccccccggaaabbbbbb..............bbbbbb........................................",
        "...........................bbbnaaaaaaaaaaaaaaaaagbbbbbjeeeeeoggggcccccccccccccccccccccccccccccccccaaaabbbbbbb...........bbbbbbb........................................",
        "...........................bbbaaaaaaaaaaaaaaaaahjbbbbbbbbbbeeggggcccccccccccccccccccccccccccccccccaaaaaallbbb........bbbbbccdbbbbbb....................................",
        "...........................bbjaaaaaaaaaaaaaaaaaeblllllbbbbbejggggggcccccccccccccccccccccccccccccccaaaaaaaajbbb.....bbbbbbbcccbbbbbb....................................",
        "...........................bbbaaaaaaaaaaaaaaaaaaaaaaallllllbbbbggggcccccccccccccccccccccccccccccccccaaaaafldbbbb...bbbccbbcccbbcibb....................................",
        "...........................bbbaaaaaaaaaaaaaaaaaaaaaaaaaaalabbbbbgggggcccccccccccccccccccccccccccccccaaaaaalbcbbb...bbccccccccccccbbbb..................................",
        "...........................bbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaallbbbbgggglccccccccccccccccccccccccccccccaaaaaaallbbbbbbbblcccccccccccbbbb..................................",
        "...........................bbbeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaebbbbgggglccccccccccccccccccccccccccccaaaaaaaaaaabbbbclleecceecccccclbb..................................",
        "...........................bbbeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaebbbbgggggccccccccccccccccccccccccccccggaaaaaaaahbbbllcleeeeeecejccccbb..................................",
        "...........................bbbeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbggggggccccccccccccccccccccccccggggaaaaaaaahbbbclceeeeeeeeeelgbbbb..................................",
        "...........................bbbeeaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbahbbbggggggccccccccccccccccccccccccggggeoaaaaaahbbbccceeeeeeeeccclbb....................................",
        "...........................bbbeeaaaaaaaaaaaaaaaaaaabbambbbbbbbbbbbbbbgggggcccccccccccccccccccccccggggpeoaaaaaahbbbccleeeeeeejlcbbbb....................................",
        "...........................bbbbbeaaaaaaaaaaaaaaaaaabbbbbbccccbbbbbbbbgggggggcccccccccccccccccgggggggeeehaaaaaahbblceeeeeeeeahfebbbb....................................",
        ".............................bbbeeaaaaaaaaaaaaaaabbbbccbbccccccccccbbgggggggggggcccccccccccccgggggoeeeeeaaaaaaabblleeeeeeeeaabbbb.......................bbbbbbbb.......",
        ".............................bbbehaaaaaaaaaaaaaaabbbbccccccccccccccbbgggggggggggcccccccccgggggggggeeeeeoaaaaaaaaacleeeeeeaaagbb.........................bbbbbbbb.......",
        ".............................bbbeeeeaaaaaaaaaaabbccbbccccpoccoeccccbbeeegggggggggggggggggggggbbbbbbbbbbbbbbaaaaaaaneeeeeeaabbbb....................bbbbbbclllcbb.......",
        ".............................bbbbbeeaaaaaaaaaaabbccbbccccoocceelcccbbeeegggggggggggggggggggbbbbbbbbbbbbbbbbjjbaaajeeeeeeebbbbb.....................bbbbbbplllpbb.......",
        "...............................bbbeeaaaaaaaaaaabbccccjocceeeeeeccccbbeeegggggggggggggggggggbbbbaaaflllcllebbbbbaaeeeeeeeebb....................bbbbbbcllllaaanbb.......",
        "...............................bbbeeeeaaaaaaaaabbcccceeeeeeeeeeeelcbbeeeeegggggggggggggggbbbbnbaaaaaaaaaaflllbbbbbbeeeebbbb....................bbbbciclaaaaabbbb.......",
        "...............................bbbbbeeaaaaaaaaabbbbccccoeeeeeeeeeccbbeeeeedggggggggggggggbbaaaaaaaaaaaaaaalllbbbbbbeeeebb..................bbbbbbclllllaaaaabbb........",
        ".................................bbbeeeeaaaaaaaahbbccccoeeeeeeeeegmbbeeeeeeeeeeggggggggeoaaaaaaaaaaaaaaaaaaaallllobbbbbbb...............bbbbbbbbbplaaaaaaaeebbb........",
        ".................................bbbeeeeoeaaaaaaobbbccceeeeeeeeeeambbeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaclllbbbbbbb...........bbbbbbplllllaaaaaeeebbbb........",
        ".................................bbbbeeeeoaaaaaeebbbbccccoeeeeeaaambbeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaflllcbbbbbbbbbbbbbbbbbbbbbbdllaaaaaaaaaeeebb..........",
        "..................................bbbbbeeeeeeaaeeeebbiccloeeeeeaaaabbeeeeeeeeeeeeeeeeeaaaaaeeeeeeaaaaaaaaaaaaaaaaaaallllllbbbbbbbbbbbbbbbilllllaaaaaaaeejbbbb..........",
        "...................................bbbbbeeeeeeeeeeebbbbccoeeeeeaaaabbbbeeeeeeeeeeeeeeeaaagheeeeeeeeoeeaaaaaaaaaaaaaaaaaaallllllllllllllllclaaaaaaaajeoeebbb............",
        ".....................................bbbeeeeeeeeeeebbbblchoeeeeaaaaabbbeeeeeeeeeeeeeejaaheeeeeeeeeeeeemaaaaaaaaaaaaaaaaaaagallallllllalllgaaaaaaaaaeeebbbbb............",
        ".......................................bbbeeeeeeeeeeebbbbaaeeeeeeaaaabbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeebbbb..............",
        ".......................................bbbbbbeeeeeeeeeebbaaaheeeeaaabbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeebbbb................",
        "........................................bbbbbeeeeeeeeeebbaaaeeeeeaaaabbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeeeeebbbb................",
        "..........................................bbbbbbbeeeeeebbbbaaeeeeaaabbbbbeeeeeeeeeeeeeebbeeeeeeeeeeeeeeeeeeeeeeeeeeeeaaaaaaaaaaaaaaaaeeeeeeeeeeeebbbb..................",
        "..............................................bbbbbbbeeeebbaaaaaaaaanbbbbeeaaaaeeeeeeeebbeeeeeeeeeeeeeeeeeeeeeeeeeeeeennnnnennnnnenneeeeeeeeebbbbbb....................",
        "...............................................bbbbbbeeeebbaaaaaaaabbbbbbbbaaaaannnnabbbbbbbbbjeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbb....................",
        "...................................................bbbbbbbbbaaaaagbbbbbbbbbaaaananaaabbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb........................",
        "...................................................bbbbbbbbbbaaaabbbb.....bbbbbbbbbbbbbb.....bbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbb........................",
        "..........................................................bbbbbbbbbb......bbbbbbbbbbbbbb.....bbbbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeebbbbbbbbbbb...........................",
        "...........................................................bbbbbbbb.................................bbbbbbbbbeeeeeeeeeeeeeeeeeebbbbbbbbb...............................",
        "...........................................................................................................bbbbbbbbbbbbbbbbbbbbbb......................................",
        "...........................................................................................................bbbbbbbbbbbbbbbbbbbbbb......................................",
        ".......................................................................................................................................................................",
        ".....bbbbbbbbbbb..................bbbbbbbbbbbbbbbbb.......bbbbbbbbbbbbb...bbbbbbbb...bbbbbbbbbbbbbbbbbbbbbb....bbbbbbbbbbbbbbbbbbb.............bbbbbbbbbbb.............",
        ".....bbbbbbbbbbb..................bbbbbbbbbbbbbbbbb......bbbbbbbbbbbbbb..bbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbb..bbbbbbbbbbbbbbbbbbbbbb.........bbbbbbbbbbbbbbb...........",
        "....bbofffffffbbbb..............bbbffffffffffffffbbbb....bblffffffffebbbbbffffffbbbbbbbfffffffffffffffffffbbbbbbffffffffffffffffgbbbb........bbbfffffffflbbb...........",
        "....bbaaaaaaaaeebbb............bbbbaaaaaaaaaaaaaabbbbbb..bbaaaaaaaaaeebbbboaaaaaeebbbbaaaaaaaaaaaaaaaaaaaajbbbbbaaaaaaaaaaaaaaaaabbbbb.....bbbbbaaaaaaaaabbbbb.........",
        "....bbgaaaaaaajeebb.........bbbbbaaaaaaaaaaaaaaaaaabbbb.bbbnaaaaaaaajjjbbboaaaaaeejbbaaaaaaaaaaaaaaaaaaaameebbbbaaaaaaaaaaaaaaaaaagbbbb....bbbhaaaaaaaaaaagbbbb........",
        "....bboaaaaaaaeeebb.........bbbaaaaaaaaaaaaaaaaaaaaaabbbbbbnaaaaaaaaeeebbbaaaaaaeeebbaaaaaaaaaaaaaaaaaaaameebbbjaaaaaaaaaaaaaaaaaaaanbbb...baaaaaaaaaaaaaaaejbbb.......",
        "....bbgaaaaaaaeejbb.........bbbaaaaaaaahjeeejaaaaaaaajjbbbbaaaaaaaaaaaebbbaaaaaajejbbaaaaaaaaaaaaaaaaaaaaaeebbbeaaaaaaaeeoehaaaaaaaajjbbbbbbmaaaaaaaaaaaaaajeebb.......",
        "....bbgaaaaaaaoeebb.........bbbaaaaaaaaheeeeeaaaaaaaaeeebbbnaaaaaaaaaaebbbaaaaaajejbbaaaaaaaaaaaaaaaaaaaameebbbeaaaaaaaeeeeeaaaaaaaaneebbbbbbaaaaaaaaaaaaaaeeebb.......",
        "....bboaaaaaaaeeebb.........bbbaaaaaaaaeeebbbaaaaaaaaeeebbbnaaaaaaaaaabbbbaaaaaaeeebbbbeeeeaaaaaaaaaeeeeeeeebbbjaaaaaaaejbbbaaaaaaaaeeebbbbaaaaaaaaeeaaaaaaaabbb.......",
        "....bbgaaaaaaaeeebbb........bbbaaaaaaaaheebbbaaaaaaaaneebbbnaaaaaaaaaabbbbaaaaaaeeebbbbeeeeaaaaaaaaaeeeeeeeebbbeaaaaaaaejbbbaaaaaaaaeeebbbbaaaaaaaajjaaaaaaaabbb.......",
        "....bboaaaaaaaeeebb.........bbbaaaaaaaaeeebbbaaaaaaaajeebbbnaaaaaaaaaaaambaaaaaaeeebbbbbbbbaaaaaaaaaeejbbbbbbbbhaaaaaaajebbbaaaaaaaaneebbbjaaaaaaejjjbbaaaaaaeebbb.....",
        "....bboaaaaaaaeeebb.........bbbaaaaaaaaeeebbbaaaaaaaajeebbbnaaaaaaaaaaaaaaaaaaaaeeebbbbbbbbaaaaaaaaaeejbbbbbbbbeaaaaaaaaaggaaaaaaaaeeeebbbbaaaaaajebbbbaaaaaaeejbb.....",
        "....bbaaaaaaaaeeebb.........bbbaaaaaaaaheebbbaaaaaaaajeebbbnaaaaaaaaaaaaaaaaaaaaeeebb....bbjaaaaaaaaeejbb....bbeaaaaaaaaaaaaaaaaaageeeebbbbaaaaaajebbbbaaaaaaeeebb.....",
        "....bbaaaaaaaaeeebb.........bbbaaaaaaaajeebbbaaaaaaaajeebbbnaaaaajbaaaaaaaaaaaaaeeebb....bbjaaaaaaaaeejbb....bbeaaaaaaaaaaaaaaaaheeeebbbbaaaaaaaaeebbbbgaaaaaaabbb.....",
        "....bbaaaaaaaaeeebbb........bbbaaaaaaaaeeebbbaaaaaaaajeebbbnaaaaaebaaaaaaaaaaaaaeeebb....bbjaaaaaaaaeeebb....bbhaaaaaaaaaaaaaaaaeebbbbbbhaaaaaaaanebbbbaaaaaaaabbbbb...",
        "....bbgaaaaaaaeeebbbbbbbbbb.bbbaaaaaaaaeeebbbaaaaaaaajeebbbnaaaaaeebbaaaaaaaaaaaeeebb....bbjaaaaaaaaeebbb....bbjaaaaaahjjbaaaaaaaabbbbbbbaaaaaaaaaaaaaaaaaaaaaajjbbb...",
        "....bboaaaaaaameebbbbbbbbbbbbbbaaaaaaaaeeebbbaaaaaaaaeeebbbnaaaaaeebbaaaaaaaaaaaeeebb....bbjaaaaaaaaeeebb....bbjaaaaaaaejboaaaaaaabbbbbbjaaaaaaaaaaaaaaaaaaaaaaeeebb...",
        "....bboaaaaaaaaaaaaaaaaaahjbbbbaaaaaaaaaaaaaaaaaaaaaameebbbnaaaaaejbbaaaaaaaaaaaeeebb....bbjaaaaaaaaeebbb....bbeaaaaaaaeebbbaaaaaaaanebbjaaaaaaaaaaaaaaaaaaaaaaeeebb...",
        "....bbaaaaaaaaaaaaaaaaaaaheebbbbgaaaaaaaaaaaaaaaaaaeeeeebbbaaaaaajjbbbbaaaaaaaaaeeebb....bbjaaaaaaaaeeebb....bbeaaaaaaaeebbbaaaaaaaaeebbjaaaaaajeeeeeeeenaaaaaaeeebb...",
        "....bbgaaaaaaaaaaaaaaaaaaheebbbbbbaaaaaaaaaaaaaaaaneeeejbbbnaaaaaeebbbbjbaaaaaaaeeebb....bbjaaaaaaaaeebbb....bbeaaaaaaaeebbbaaaaaaaaeebbbaaaaaajeeeeeeeenaaaaaaeeebb...",
        "....bbaaaaaaaaaaaaaaaaaaaoeebbbbbbjaaaaaaaaaaaaaajeeebbbbbbnaaaaaeebbbbbbaaaaaaaeeebb....bbaaaaaaaaaeeebb....bbhaaaaaaaeebbbaaaaaaaaneebhaaaaaaeebbbbbbbbaaaaaaeeebb...",
        "....bbbbeeeeeeeeeeeeeeeeeeeebbbbbbbbbjjeeeeeeeeeeeebbbbbbbbbbeeeeeebbbbbbbbeeeeeeeebb....bbbbjeeeeeeeeebb....bbbbjeeeeejebbbbbeeeeeeeebbbbbjjeeeebbbbbbbbbeeeeeeeebb...",
        "......bbjeeeeeeeeeeeeeeeeeeebbbbbbbbbjjeeeeeeeeeeeebbb....bbbeeeeeebb..jbbbeeeeeeeebb......bbjeeejeeeeebb......bbeeeeeeeebbbbbeeeeeeeebbbbbjeeeeebb....bbbjjeeeeeebb...",
        "......bbbbbbbbbbbbbbbbbbbbbbbbb....bbbbbbbbbbbbbbbbbbb.....bbbbbbbbbb...bbbbbbbbbbbbb.......bbbbbbbbbbbbb.......bbbbbbbbbbb..bbbbbbbbbbbbbbbbbbbbbb.....bbbbbbbbbbbb...",
        ".......bbbbbbbbbbbbbbbbbbbbbbbb....bbbbbbbbbbbbbbbbb........bbbbbbbbb.....bbbbbbbbbb........bbbbbbbbbbbbj.......bbbbbbbbbb...bbbbbbbbbb..bbbbbbbbb.......bbbbbbbbbb....",
        "..bbbbbbbbbb..bbbbbbbbbjbbbbbbb..bbbbbbbbbbbbbb....bbbbbbbb.bbbbbbbb....bbbbbbbbbbbb...bbbbbbbbbbbbbbb..bbbbbbbbbbbbbbbb...bbbbbbbb..bbbbbbbbbbbbbbbb...bbbbbbbbbbbbb..",
        ".bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbb...bbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbbbbbbbbbbbbbbbbbbbbbbbb..bbbbbbbbbbbbbbb.",
        "bbbcccccccjbbbbccccccbbbbdccccbbbbcccccccccccbbbbbbbccccccjbbcccccbbbbbbbcccccccccbbbbbbcccccccccccccbbbbcccccccccccccbbbbbbccccccbbbbcccccccccccccbbbjbbiccccccccccbbb",
        "bbbccccccejjbbbccccccjbbbdccccjbbbcccccccccccccbbbbbccccccjbjcccccijbbbcjcccccccccicbbbbcccccccccccccjbbbcccccccccccccicbbbbccccccjbbblccccccccccccjjbbbccccccccccccbbb",
        "bbbcccccccjjbbbccccccjjbbdccccjbbbcccccccccccccbbbbbccccccbbbcccccijbbbccccccccccccijbbbcccccccccccccjbbbcccccccccccccccjbbbccccccjjbbcccccccccccccjjbbbccccccccccccjjb",
        "bbbcccccccjjbbbccccccccbbcccccjbbbccccccllccccccjjbbecccccjbbcccccijbbbccccccbccccccjbbbeebcccccciebijbbbccccccbjbbcccccjjbbccccccjjbbcccccccjjjjjjjjbbbccccccceiiijjbb",
        ".bbccccccojjbbbccccccccibcccccjjbbcccccjjbccccccjjbbecccccjbbcccccijbbbccccccbbjjjjjjbbbjjjecccccjjjjjbbbccccccjjbccccccjjbbccccccjjbbiccccccbjjjjjjbbbbcccccebjjjjjjbb",
        ".bbcccccccjjbbbccccccccjbcccccjbbbcccccjjbccccccjjbbccccccjbbcccccijbbbcccccccecbbbbbbbbbbbjcccccjjbbbbbbccccccbbbdcccccjjbbccccccjjbbcccccccccbcbbbbbbbccccccjjbbbbbb.",
        ".bbcccccccjjbbbcccccccccccccccjbbbcccccjjbccccccjjbbjcccccjjbcccccijbbbcccccccccbbbbbbbbbbbccccccjjbbbbbbcccccccibccccccjjbbccccccjjbbicccccccccccjbbbbbccccccccbbbbbb.",
        ".bbccccccojjbbbcccccccccccccccjbbbcccccjjbccccccjjbbccccccjjbcccccijbbbbbbcccccccccbbb...bbjcccccjjbb..bbcccccccccccccjjjjbbccccccjjbbccccccccccccjjbbbbbjccccccccdbbb.",
        "bbbccccccojjbbbcccccccccccccccjbbbccccccjbccccccjjbbccccccjbbcccccjjbbbbbbcbdbcccccbbbb..bbjcccccjjbb..bbccccccccccccjjjbbbbccccccjjbbccccccccccccbjbbbbbbdccbccccccbbb",
        "bbbccccccojjbbbcccccjcccccccccjbbbcccccjjbccccccjjbbccccccjbbcccccijbbbbbbbbbbcccccbjbb..bbccccccjjbb..bbccccccbbccccebbbbbbccccccjjbblccccccjjjjjjjbbbbbbbbbbccccccjbb",
        "bbbcccccccjjbbbcccccjcccccccccjjbbcccccjjbccccccjjbbecccccbbbccccccjbbbccccbbbcccccbjbb..bbjcccccjjbb..bbccccccbbocccccbbbbbccccccjjbbcccccccjbbbbbbbbbcccccbbccccccjjb",
        "bbbcccccccjjbbbcccccjbcccccccojbbbccccccccccccccjjbbecccccccccccccjjbbbccccccccccccbjbb..bbjcccccjjbb..bbccccccbbbbcccccbbbbccccccjjbbcccccccciicccbbbbcccccccccccccjbb",
        "bbbccccccojjbbbcccccjbbcccccccjbbbcccccccccccccjjjbbccccccccccccccjjbbbccccccccccccjjbb..bbecccccjjbb..bbccccccebbdcccccjbbbccccccjbbbcccccccccccccjjbbccccccccccccbjbb",
        "bbbcccccccjjbbbccccojbbpccccccjbbbcccccccccccbjjjbbbbbccccccccccjjjbbbbbbccccccccbjjjbb..bbecccccjjbb..bbccccccejbbcccccjjbbccccccjbbbcccccccccccccjjbbbbcccccccccjjjbb",
        "bbbbjjjjjjjjbbbbjjjjjbbbbjjjjjjbbbbjjjjjjjjjjjjbbbb.bbbbjjjjjjjjjbbbbbbbbbjjjjjjjjjbbbb..bbbbjjjjjjbb..bbbjjjjjjbbbbjjjjjjbbbejjjjjjbbbbjjjjjjjjjjjjjbbbbbjjjjjjjjjbbbb",
        "..bbbbjjjjjbbbbbbjbbjbbbbjjjjjjbbbbbjjjjjjjjjjbbb...bbbbbjjjjbjjbbbb...bbbbbbjjjjjbbbb....bbbjjjjjbbb...bbbjjjjbbbbbbjjbjbbbbbjbjbjbbbbbbjjjjjjjjjjjbb.bbbbjjjjjjjjbbb.",
        "...bbbbbbbbbb..bbbbbbb..bbbbbbbb..bbbbbbbbbbbbb.......bbbbbbbbbbbb.......bbbbbbbbbbb........bbbbbbb......bbbbbbbb..bbbbbbb..bbbbbbbb...bbbbbbbbbbbbbb....bbbbbbbbbbb...",
    ]
}
